-- Create schema
CREATE SCHEMA IF NOT EXISTS crm;

-- Common Types

CREATE TYPE app.mutation_result AS (
    id UUID,
    updated_fields TEXT[],
    status TEXT,
    message TEXT,
    object_data JSONB,
    extra_metadata JSONB
);

COMMENT ON TYPE app.mutation_result IS
  '@fraiseql:type name=MutationResult';

COMMENT ON COLUMN app.mutation_result.id IS
  '@fraiseql:field name=id,type=UUID,description=Entity identifier';

COMMENT ON COLUMN app.mutation_result.updated_fields IS
  '@fraiseql:field name=updatedFields,type=[String],description=Fields that were modified in this mutation';

COMMENT ON COLUMN app.mutation_result.status IS
  'Status: success, failed:*, warning:*';

COMMENT ON COLUMN app.mutation_result.message IS
  '@fraiseql:field name=message,type=String,description=Human-readable success or error message';

COMMENT ON COLUMN app.mutation_result.object_data IS
  '@fraiseql:field name=object,type=JSON,description=Complete entity data after mutation';

COMMENT ON COLUMN app.mutation_result.extra_metadata IS
  '@fraiseql:field name=extra,type=JSON,description=Additional metadata including side effects and impact information';



CREATE TYPE app.type_deletion_input AS (
    id UUID
);

COMMENT ON TYPE app.type_deletion_input IS
  '@fraiseql:input name=DeletionInput';


-- Entity Table
-- ============================================================================
-- Table: crm.tb_contact
-- ============================================================================
-- [Table: CON | Customer contact information]
-- ============================================================================

CREATE TABLE crm.tb_contact (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_contact INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Multi-Tenancy: Denormalized from JWT (CRITICAL for security)
    -- ========================================================================
    tenant_id UUID NOT NULL,

    -- ========================================================================
    -- Multi-Tenancy: Optional business FK to organization
    -- ========================================================================
    -- Note: Only add fk_organization if entity belongs to specific org unit
    -- (not just tenant isolation). Comment out if not needed.
    -- fk_organization INTEGER,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    email TEXT,
    first_name TEXT,
    last_name TEXT,
    status TEXT,
    phone TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================    fk_company INTEGER,
    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_contact_id_key UNIQUE (id)
    ,CONSTRAINT chk_tb_contact_status_enum CHECK (status IN ('lead', 'qualified', 'customer')));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
ALTER TABLE ONLY crm.tb_contact
    ADD CONSTRAINT tb_contact_fk_company_fkey
    FOREIGN KEY (fk_company) REFERENCES crm.tb_company(pk_company);-- ============================================================================
-- Multi-Tenancy Indexes (CRITICAL for performance & RLS)
-- ============================================================================
CREATE INDEX idx_tb_contact_tenant ON crm.tb_contact(tenant_id);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE crm.tb_contact IS
'Customer contact information.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN crm.tb_contact.pk_contact IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN crm.tb_contact.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Multi-Tenancy columns
COMMENT ON COLUMN crm.tb_contact.tenant_id IS 'Denormalized tenant identifier from JWT token (security context).';
-- COMMENT ON COLUMN crm.tb_contact.fk_organization IS 'Optional business FK to organization unit (uncomment if needed).';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN crm.tb_contact.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN crm.tb_contact.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN crm.tb_contact.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN crm.tb_contact.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN crm.tb_contact.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN crm.tb_contact.deleted_by IS 'User or system who deleted the record.';

-- Input Type: qualify_lead

-- ============================================================================
-- INPUT TYPE: type_qualify_lead_input
-- For action: qualify_lead
-- ============================================================================
CREATE TYPE app.type_qualify_lead_input AS (

    id UUID

);

-- FraiseQL metadata
COMMENT ON TYPE app.type_qualify_lead_input IS
'Input parameters for Qualify Lead.

@fraiseql:composite
name: QualifyLeadInput
tier: 2';


-- Field metadata

COMMENT ON COLUMN app.type_qualify_lead_input.id IS
'Id (required).

@fraiseql:field
name: id
type: UUID!
required: true';



-- Input Type: create_contact

-- ============================================================================
-- INPUT TYPE: type_create_contact_input
-- For action: create_contact
-- ============================================================================
CREATE TYPE app.type_create_contact_input AS (

    email TEXT,

    first_name TEXT,

    last_name TEXT,

    company_id UUID,

    status TEXT,

    phone TEXT

);

-- FraiseQL metadata
COMMENT ON TYPE app.type_create_contact_input IS
'Input parameters for Create Contact.

@fraiseql:composite
name: CreateContactInput
tier: 2';


-- Field metadata

COMMENT ON COLUMN app.type_create_contact_input.email IS
'Email (optional).

@fraiseql:field
name: email
type: String
required: false';

COMMENT ON COLUMN app.type_create_contact_input.first_name IS
'First_Name (optional).

@fraiseql:field
name: first_name
type: String
required: false';

COMMENT ON COLUMN app.type_create_contact_input.last_name IS
'Last_Name (optional).

@fraiseql:field
name: last_name
type: String
required: false';

COMMENT ON COLUMN app.type_create_contact_input.company_id IS
'Company reference (optional).

@fraiseql:field
name: company_id
type: UUID
required: false
references: Company';

COMMENT ON COLUMN app.type_create_contact_input.status IS
'Status (lead, qualified, customer).

@fraiseql:field
name: status
type: String
required: false
enumValues: lead, qualified, customer';

COMMENT ON COLUMN app.type_create_contact_input.phone IS
'Phone (optional).

@fraiseql:field
name: phone
type: String
required: false';



-- Indexes
CREATE INDEX idx_tb_contact_id
    ON crm.tb_contact USING btree (id);

CREATE INDEX idx_tb_contact_company
    ON crm.tb_contact USING btree (fk_company);

CREATE INDEX idx_tb_contact_status
    ON crm.tb_contact USING btree (status);

-- Foreign Keys
ALTER TABLE ONLY crm.tb_contact
    ADD CONSTRAINT tb_contact_company_fkey
    FOREIGN KEY (fk_company) REFERENCES crm.tb_company(pk_company);