"""
Tests for Table Generator (Team B)
"""

import pytest

# pytestmark = pytest.mark.skip(reason="Minor assertion format differences - deferred to post-beta")

from src.generators.schema.naming_conventions import NamingConventions
from src.generators.schema.schema_registry import SchemaRegistry
from src.generators.table_generator import TableGenerator
from tests.fixtures.mock_entities import (
    mock_contact_entity,
    mock_simple_entity,
)


class TestTableGenerator:
    """Test table DDL generation"""

    @pytest.fixture
    def generator(self):
        """Create table generator instance"""
        naming_conventions = NamingConventions()
        schema_registry = SchemaRegistry(naming_conventions.registry)
        return TableGenerator(schema_registry)

    def test_generate_simple_table(self, generator):
        """Test generating DDL for simple entity"""
        entity = mock_simple_entity()

        ddl = generator.generate_table_ddl(entity)

        # Check basic structure
        assert "CREATE TABLE inventory.tb_product" in ddl
        assert "pk_product INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
        assert "id UUID DEFAULT gen_random_uuid() NOT NULL" in ddl
        assert "name TEXT NOT NULL" in ddl
        assert "price INTEGER NOT NULL" in ddl
        assert "created_at TIMESTAMPTZ NOT NULL DEFAULT now()" in ddl

    def test_generate_contact_table(self, generator):
        """Test generating DDL for contact entity with enums and refs"""
        entity = mock_contact_entity()

        ddl = generator.generate_table_ddl(entity)

        # Check Trinity pattern
        assert "CREATE TABLE crm.tb_contact" in ddl
        assert "pk_contact INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
        assert "id UUID DEFAULT gen_random_uuid() NOT NULL" in ddl

        # Check business fields
        assert "email TEXT NOT NULL" in ddl
        assert "status TEXT NOT NULL" in ddl
        assert "fk_company INTEGER" in ddl

    def test_table_comments_with_fraiseql_yaml_format(self, generator):
        """Table and column comments should use FraiseQL YAML format"""
        entity = mock_contact_entity()

        ddl = generator.generate_table_ddl(entity)

        # Check table comment with @fraiseql:type
        # Note: Template adds trailing newline before closing quote
        expected_table_comment = """COMMENT ON TABLE crm.tb_contact IS
'CRM contact entity.

@fraiseql:type
trinity: true
';"""
        assert expected_table_comment in ddl

        # Check column comment with @fraiseql:field
        expected_id_comment = """COMMENT ON COLUMN crm.tb_contact.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';"""
        assert expected_id_comment in ddl

        # Check enum constraint
        assert "CHECK (status IN ('lead', 'qualified', 'customer'))" in ddl

        # Check foreign key
        assert "REFERENCES crm.tb_company(pk_company)" in ddl

    def test_generate_foreign_keys_ddl(self, generator):
        """Test foreign key DDL generation"""
        entity = mock_contact_entity()

        fk_ddl = generator.generate_foreign_keys_ddl(entity)

        assert "ALTER TABLE ONLY crm.tb_contact" in fk_ddl
        assert "ADD CONSTRAINT tb_contact_company_fkey" in fk_ddl
        assert "FOREIGN KEY (fk_company) REFERENCES crm.tb_company(pk_company)" in fk_ddl

    def test_generate_indexes_ddl(self, generator):
        """Test index DDL generation"""
        entity = mock_contact_entity()

        idx_ddl = generator.generate_indexes_ddl(entity)

        # UUID index
        assert "CREATE INDEX idx_tb_contact_id" in idx_ddl
        assert "ON crm.tb_contact USING btree (id)" in idx_ddl

        # Foreign key index
        assert "CREATE INDEX idx_tb_contact_company" in idx_ddl
        assert "ON crm.tb_contact USING btree (fk_company)" in idx_ddl

        # Enum index
        assert "CREATE INDEX idx_tb_contact_status" in idx_ddl
        assert "ON crm.tb_contact USING btree (status)" in idx_ddl

    def test_field_type_mappings(self, generator):
        """Test various field type mappings"""
        # Test that all supported types are mapped
        mappings = generator.TYPE_MAPPINGS

        assert mappings["text"] == "TEXT"
        assert mappings["integer"] == "INTEGER"
        assert mappings["boolean"] == "BOOLEAN"
        assert mappings["date"] == "DATE"
        assert mappings["timestamp"] == "TIMESTAMPTZ"
        assert mappings["uuid"] == "UUID"
        assert mappings["json"] == "JSONB"
