"""Tests for SQL table parsing functionality."""

from reverse_engineering.table_parser import SQLTableParser


class TestSQLTableParser:
    """Test cases for SQL table parsing."""

    def test_parse_simple_table(self):
        """Test parsing a simple CREATE TABLE statement."""
        sql = """
        CREATE TABLE catalog.tb_manufacturer (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL
        );
        """

        parser = SQLTableParser()
        result = parser.parse_table(sql)

        assert result.schema == "catalog"
        assert result.table_name == "tb_manufacturer"
        assert len(result.columns) == 2
        assert result.columns[0].name == "id"
        assert result.columns[0].type == "INTEGER"
        assert result.columns[1].name == "name"
        assert result.columns[1].type == "TEXT"
        assert result.columns[1].nullable == False

    def test_map_column_types(self):
        """Test mapping PostgreSQL types to SpecQL types."""
        sql = """
        CREATE TABLE test.tb_product (
            name TEXT NOT NULL,
            price NUMERIC(10,2),
            quantity INTEGER,
            active BOOLEAN DEFAULT true,
            created_at TIMESTAMPTZ
        );
        """

        parser = SQLTableParser()
        result = parser.parse_table(sql)

        # Should map PostgreSQL types to SpecQL types
        assert result.columns[0].specql_type == "text"
        assert result.columns[1].specql_type == "decimal"
        assert result.columns[2].specql_type == "integer"
        assert result.columns[3].specql_type == "boolean"
        assert result.columns[4].specql_type == "timestamptz"

    def test_parse_constraints(self):
        """Test parsing of table constraints."""
        sql = """
        CREATE TABLE catalog.tb_manufacturer (
            id INTEGER PRIMARY KEY,
            identifier TEXT NOT NULL,
            abbreviation CHAR(2) NOT NULL,
            CONSTRAINT tb_manufacturer_identifier_key UNIQUE (identifier)
        );
        """

        parser = SQLTableParser()
        result = parser.parse_table(sql)

        assert result.primary_key == ["id"]
        assert ["identifier"] in result.unique_constraints
        assert result.columns[1].nullable == False
        assert result.columns[2].nullable == False
