"""Tests for Trinity pattern detection functionality."""

from reverse_engineering.fk_detector import ForeignKeyDetector
from reverse_engineering.table_parser import SQLTableParser
from reverse_engineering.trinity_detector import TrinityPatternDetector


class TestTrinityPatternDetector:
    """Test cases for Trinity pattern detection."""

    def test_detect_trinity_fields(self):
        """Test detection of Trinity pattern fields."""
        sql = """
        CREATE TABLE catalog.tb_manufacturer (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pk_manufacturer UUID DEFAULT gen_random_uuid() NOT NULL,
            identifier TEXT NOT NULL,
            name TEXT,
            created_at TIMESTAMPTZ DEFAULT now()
        );
        """

        parser = SQLTableParser()
        parsed_table = parser.parse_table(sql)

        detector = TrinityPatternDetector()
        result = detector.detect(parsed_table)

        assert result.has_trinity_pattern is True
        assert result.id_field == "id"
        assert result.pk_field == "pk_manufacturer"
        assert result.identifier_field == "identifier"
        assert result.business_fields == ["name"]  # Excludes id, pk_*, identifier, audit

    def test_detect_foreign_keys(self):
        """Test detection of foreign key relationships."""
        main_sql = """
        CREATE TABLE catalog.tb_manufacturer (
            pk_manufacturer UUID PRIMARY KEY,
            fk_company UUID,
            name TEXT
        );
        """

        alter_sql = """
        ALTER TABLE catalog.tb_manufacturer
            ADD CONSTRAINT tb_manufacturer_fk_company_fkey
            FOREIGN KEY (fk_company)
            REFERENCES management.tb_organization(pk_organization);
        """

        parser = SQLTableParser()
        parsed_table = parser.parse_table(main_sql)

        detector = ForeignKeyDetector()
        foreign_keys = detector.detect(parsed_table, [alter_sql])

        assert len(foreign_keys) == 1
        fk = foreign_keys[0]
        assert fk.column == "fk_company"
        assert fk.references_table == "tb_organization"
        assert fk.references_schema == "management"
        assert fk.references_column == "pk_organization"

        # Should infer entity name from table name
        assert fk.entity_name == "Organization"  # tb_organization → Organization
