"""
Init registry subcommand - Create schema registry for table codes.
"""

from pathlib import Path

import click

from cli.utils.error_handler import handle_cli_error


@click.command()
@click.option("--output", "-o", default="entities/domain_registry.yaml", help="Output file path")
@click.option("--domains", multiple=True, help="Domain names to include")
@click.option(
    "--template",
    type=click.Choice(["basic", "extended"]),
    default="basic",
    help="Registry template",
)
def registry(output, domains, template, **kwargs):
    """Create a domain registry for table code management.

    Initializes a YAML registry that maps entities to hexadecimal table codes
    for consistent, hierarchical table naming across your database schema.

    Templates:
    - basic: Standard registry with common domains
    - extended: Comprehensive registry with detailed domain structure

    Examples:

        specql init registry
        specql init registry --domains=crm --domains=inventory -o registry.yaml
        specql init registry --template=extended
    """
    with handle_cli_error():
        output_path = Path(output)
        output.info(f"📋 Creating domain registry: {output_path}")

        # Default domains if none specified
        if not domains:
            if template == "basic":
                domains = ["app", "auth", "crm", "inventory", "finance"]
            else:
                domains = [
                    "app",
                    "auth",
                    "crm",
                    "inventory",
                    "finance",
                    "analytics",
                    "audit",
                    "notification",
                    "integration",
                ]

        # Generate registry content
        registry_content = """# Domain Registry for Table Code Management
# Maps entities to hexadecimal table codes for consistent naming
# Generated by: specql init registry

version: "1.0"
description: "Table code registry for hierarchical schema organization"

domains:
"""

        # Add domains with sample entities
        domain_templates = {
            "app": ["User", "Session", "Setting"],
            "auth": ["User", "Role", "Permission", "UserRole"],
            "crm": ["Contact", "Company", "Lead", "Opportunity"],
            "inventory": ["Product", "Category", "Stock", "Supplier"],
            "finance": ["Invoice", "Payment", "Account", "Transaction"],
            "analytics": ["Event", "Metric", "Report", "Dashboard"],
            "audit": ["AuditLog", "ChangeHistory", "AccessLog"],
            "notification": ["Notification", "Template", "Queue"],
            "integration": ["Webhook", "ApiKey", "Connection"],
        }

        table_code_counter = 0x100000  # Start at 100000

        for domain in domains:
            registry_content += f"\n  {domain}:\n"
            registry_content += f'    description: "{domain.title()} domain entities"\n'
            registry_content += "    entities:\n"

            entities = domain_templates.get(domain, [f"{domain.title()}Entity"])
            for entity in entities:
                # Generate hexadecimal table code
                table_code = f"{table_code_counter:06X}"
                registry_content += f'      {entity}: "{table_code}"\n'
                table_code_counter += 0x1000  # Increment by 4096 for domain separation

        # Add registry metadata
        registry_content += """
# Registry Configuration
config:
  code_format: "hexadecimal"
  code_length: 6
  domain_separator: true
  auto_increment: true

# Usage Notes:
# - Table codes are 6-digit hexadecimal (e.g., 100000, 200000)
# - Domain separation: ~4000 codes per domain
# - Use with: specql generate --use-registry
# - Update this file as you add new entities
"""

        # Create output directory and write file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(registry_content)

        output.success(f"✅ Domain registry created: {output_path}")
        output.info("📊 Registry details:")
        output.info(f"  • Domains: {len(domains)}")
        output.info(f"  • Template: {template}")
        output.info("  • Format: 6-digit hexadecimal codes")

        output.info("\n🚀 Next steps:")
        output.info("  1. Review and customize entity mappings")
        output.info("  2. Use with: specql generate --use-registry")
        output.info("  3. Update as you add new entities")

        output.warning("Full registry integration pending in Phase 5")
