-- Test Metadata Schema
-- Foundation for automated test and seed data generation
-- Generated: 2025-11-09

CREATE SCHEMA IF NOT EXISTS test_metadata;

-- Table 1: tb_entity_test_config
-- High-level configuration for each entity's testing
CREATE TABLE test_metadata.tb_entity_test_config (
    -- Primary key
    pk_entity_test_config INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Entity identification
    entity_name TEXT NOT NULL UNIQUE,           -- "Contact"
    schema_name TEXT NOT NULL,                  -- "crm"
    table_name TEXT NOT NULL,                   -- "tb_contact"

    -- UUID encoding configuration
    table_code INTEGER NOT NULL,                -- 123210 (for UUID encoding)
    entity_code TEXT NOT NULL,                  -- "CON" (3-char abbreviation)
    base_uuid_prefix TEXT NOT NULL,             -- "012321" (6-digit prefix)

    -- Multi-tenancy
    is_tenant_scoped BOOLEAN DEFAULT TRUE,
    default_tenant_id UUID DEFAULT '22222222-2222-2222-2222-222222222222',
    default_user_id UUID DEFAULT '01232022-0000-0000-0000-000000000001',

    -- Seed data defaults
    default_seed_count INTEGER DEFAULT 10,
    seed_strategy TEXT DEFAULT 'realistic',     -- 'realistic', 'edge_cases', 'performance', 'minimal'

    -- Test generation flags
    enable_crud_tests BOOLEAN DEFAULT TRUE,
    enable_action_tests BOOLEAN DEFAULT TRUE,
    enable_constraint_tests BOOLEAN DEFAULT TRUE,
    enable_dedup_tests BOOLEAN DEFAULT FALSE,
    enable_fk_tests BOOLEAN DEFAULT TRUE,

    -- Metadata
    source_yaml_path TEXT,                      -- Path to SpecQL file
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    CONSTRAINT valid_seed_strategy CHECK (seed_strategy IN ('realistic', 'edge_cases', 'performance', 'minimal'))
);

-- Table 2: tb_field_generator_mapping
-- Describes how to generate value for each field
CREATE TABLE test_metadata.tb_field_generator_mapping (
    -- Primary key
    pk_field_gen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign key to entity
    fk_entity_test_config INTEGER NOT NULL REFERENCES test_metadata.tb_entity_test_config(pk_entity_test_config),

    -- Field identification
    field_name TEXT NOT NULL,
    field_type TEXT NOT NULL,                   -- "text", "email", "ref(Company)", "enum(lead,qualified)"
    postgres_type TEXT NOT NULL,                -- "TEXT", "INTEGER", "NUMERIC(19,4)"

    -- Generator strategy
    generator_type TEXT NOT NULL,               -- 'random', 'fk_resolve', 'group_leader', 'group_dependent', 'fixed', 'sequence'
    generator_function TEXT,                    -- SQL function name: 'test_random_email'
    generator_params JSONB,                     -- Parameters for generator

    -- For FK resolution
    fk_target_entity TEXT,                      -- "Company"
    fk_target_schema TEXT,                      -- "crm"
    fk_target_table TEXT,                       -- "tb_company"
    fk_target_pk_field TEXT,                    -- "pk_company"
    fk_resolution_query TEXT,                   -- Custom query for FK lookup
    fk_filter_conditions TEXT,                  -- WHERE conditions for FK query
    fk_dependencies TEXT[],                     -- Other fields needed for FK resolution (e.g., ['tenant_id'])

    -- Group leader pattern
    generator_group TEXT,                       -- "address_group", "location_group"
    is_group_leader BOOLEAN DEFAULT FALSE,      -- This field executes the query
    group_leader_field TEXT,                    -- Name of group leader (if this is dependent)
    group_dependency_fields TEXT[],             -- Fields returned by group leader query

    -- Constraints & validation
    nullable BOOLEAN DEFAULT TRUE,
    unique_constraint BOOLEAN DEFAULT FALSE,
    validation_pattern TEXT,                    -- Regex for validation
    check_constraint TEXT,                      -- SQL CHECK expression

    -- Seed data hints
    example_values TEXT[],                      -- Example values for seed
    seed_distribution JSONB,                    -- Statistical distribution: {"min": 1, "max": 100, "mean": 50}
    enum_values TEXT[],                         -- For enum types

    -- Metadata
    priority_order INTEGER DEFAULT 100,         -- Generation order (lower = earlier)
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    UNIQUE (fk_entity_test_config, field_name),
    CONSTRAINT valid_generator_type CHECK (generator_type IN ('random', 'fk_resolve', 'group_leader', 'group_dependent', 'fixed', 'sequence'))
);

-- Table 3: tb_test_scenarios
-- Define test scenarios for each entity
CREATE TABLE test_metadata.tb_test_scenarios (
    -- Primary key
    pk_scenario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign key to entity
    fk_entity_test_config INTEGER NOT NULL REFERENCES test_metadata.tb_entity_test_config(pk_entity_test_config),

    -- Scenario identification
    scenario_code INTEGER NOT NULL,             -- 0, 1000, 2000, etc. (for UUID encoding)
    scenario_name TEXT NOT NULL,                -- "happy_path_create", "duplicate_email"
    scenario_type TEXT NOT NULL,                -- 'happy_path', 'constraint_violation', 'dedup', 'custom_action', 'fk_violation'

    -- Test generation
    test_function_name TEXT,                    -- "test_create_contact_duplicate_email"
    target_action TEXT,                         -- For action tests: "qualify_lead"
    input_overrides JSONB,                      -- Override default field values: {"email": "duplicate@example.com"}
    expected_result TEXT NOT NULL,              -- 'success', 'error'
    expected_error_code TEXT,                   -- 'duplicate_key_violation', 'fk_violation'
    expected_status_pattern TEXT,               -- Regex: 'failed:.*'

    -- Seed data
    seed_count INTEGER DEFAULT 1,
    requires_dependencies BOOLEAN DEFAULT TRUE, -- Need parent entities seeded?
    dependency_entities TEXT[],                 -- ["Company", "User"] - need these first

    -- Test execution
    setup_sql TEXT,                             -- SQL to run before test
    teardown_sql TEXT,                           -- SQL to run after test

    -- Metadata
    description TEXT,
    test_category TEXT,                         -- 'crud', 'action', 'constraint', 'performance'
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    UNIQUE (fk_entity_test_config, scenario_code),
    CONSTRAINT valid_scenario_type CHECK (scenario_type IN ('happy_path', 'constraint_violation', 'dedup', 'custom_action', 'fk_violation', 'performance')),
    CONSTRAINT valid_expected_result CHECK (expected_result IN ('success', 'error'))
);

-- Indexes
CREATE INDEX idx_entity_test_config_entity_name ON test_metadata.tb_entity_test_config(entity_name);
CREATE INDEX idx_entity_test_config_schema ON test_metadata.tb_entity_test_config(schema_name);
CREATE INDEX idx_field_gen_entity ON test_metadata.tb_field_generator_mapping(fk_entity_test_config);
CREATE INDEX idx_field_gen_type ON test_metadata.tb_field_generator_mapping(generator_type);
CREATE INDEX idx_field_gen_group ON test_metadata.tb_field_generator_mapping(generator_group) WHERE generator_group IS NOT NULL;
CREATE INDEX idx_scenario_entity ON test_metadata.tb_test_scenarios(fk_entity_test_config);
CREATE INDEX idx_scenario_type ON test_metadata.tb_test_scenarios(scenario_type);
CREATE INDEX idx_scenario_enabled ON test_metadata.tb_test_scenarios(enabled) WHERE enabled = TRUE;

-- Comments
COMMENT ON SCHEMA test_metadata IS 'Test metadata for automated test and seed data generation';
COMMENT ON TABLE test_metadata.tb_entity_test_config IS 'High-level configuration for each entity''s testing';
COMMENT ON TABLE test_metadata.tb_field_generator_mapping IS 'Describes how to generate values for each field';
COMMENT ON TABLE test_metadata.tb_test_scenarios IS 'Define test scenarios for each entity';