"""Integration test for complete Trinity pattern generation"""

from src.generators.schema.trinity_schema_orchestrator import TrinitySchemaOrchestrator
from src.core.ast_models import Entity, FieldDefinition


def test_complete_trinity_generation():
    """Test that both tb_ and tv_ tables are generated with all features"""
    # Create a comprehensive entity with all features
    entity = Entity(
        name="Contact",
        schema="crm",
        description="Customer contact with full Trinity pattern",
        fields={
            "email": FieldDefinition(name="email", type_name="text", nullable=False, description="Email address"),
            "company": FieldDefinition(name="company", type_name="ref", reference_entity="Company", description="Company reference"),
            "status": FieldDefinition(name="status", type_name="enum", values=["lead", "qualified", "customer"], description="Contact status"),
            "age": FieldDefinition(name="age", type_name="integer", description="Contact age"),
            "price": FieldDefinition(name="price", type_name="decimal", description="Contact value"),
            "phone": FieldDefinition(name="phone", type_name="text", description="Phone number"),
        }
    )

    orchestrator = TrinitySchemaOrchestrator()

    # Act
    files = orchestrator.generate_schema([entity])

    # Assert - Should generate multiple files
    assert len(files) >= 4  # tb_, tv_, helpers, vector, fulltext

    # Check base table generation
    base_table_files = [f for f in files if f.name.startswith("tb_")]
    assert len(base_table_files) == 1
    base_table = base_table_files[0]

    # Verify Trinity pattern in base table
    content = base_table.content
    assert "CREATE TABLE crm.tb_contact" in content
    assert "pk_contact INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in content
    assert "id UUID DEFAULT gen_random_uuid() NOT NULL" in content
    assert "created_at TIMESTAMPTZ NOT NULL DEFAULT now()" in content
    assert "updated_at TIMESTAMPTZ NOT NULL DEFAULT now()" in content
    assert "deleted_at TIMESTAMPTZ" in content
    assert "email VARCHAR(255) NOT NULL" in content  # Context-aware inference
    assert "phone VARCHAR(50)" in content  # Phone-specific inference
    assert "age SMALLINT" in content  # Age inference
    assert "price NUMERIC(10,2)" in content  # Money inference
    assert "CONSTRAINT chk_tb_contact_status CHECK (status IN ('lead', 'qualified', 'customer'))" in content

    # Check table view generation
    table_view_files = [f for f in files if f.name.startswith("tv_")]
    assert len(table_view_files) == 1
    table_view = table_view_files[0]

    # Verify table view features
    tv_content = table_view.content
    assert "CREATE TABLE crm.tv_contact" in tv_content
    assert "data JSONB NOT NULL" in tv_content
    assert "refreshed_at TIMESTAMPTZ DEFAULT now()" in tv_content
    assert "jsonb_build_object" in tv_content
    assert "CREATE TRIGGER trg_refresh_tv_contact" in tv_content

    # Check helper functions
    helper_files = [f for f in files if "helper" in f.name.lower() or "pk(" in f.content or "id(" in f.content]
    assert len(helper_files) >= 1

    # Check for Trinity helper functions
    all_content = "\n".join(f.content for f in files)
    assert "CREATE OR REPLACE FUNCTION crm.contact_pk" in all_content
    assert "CREATE OR REPLACE FUNCTION crm.contact_id" in all_content

    # Check vector features (always generated in this test setup)
    assert "vector(384)" in all_content
    assert "USING hnsw" in all_content
    assert "search_contact_by_embedding" in all_content

    # Check full-text features (always generated in this test setup)
    assert "tsvector" in all_content
    assert "to_tsvector('english'" in all_content
    assert "search_contact_by_text" in all_content

    # Check FraiseQL annotations
    assert "@fraiseql:entity" in all_content
    assert "@fraiseql:type" in all_content
    assert "@fraiseql:field" in all_content
    assert "@fraiseql:helper" in all_content
    assert "@fraiseql:query" in all_content


def test_schema_orchestrator_integration():
    """Test the full schema orchestrator with multiple entities"""
    entities = [
        Entity(
            name="Contact",
            schema="crm",
            fields={
                "email": FieldDefinition(name="email", type_name="text", nullable=False),
                "company_id": FieldDefinition(name="company_id", type_name="ref", reference_entity="Company"),
            }
        ),
        Entity(
            name="Company",
            schema="crm",
            fields={
                "name": FieldDefinition(name="name", type_name="text", nullable=False),
                "industry": FieldDefinition(name="industry", type_name="text"),
            }
        )
    ]

    orchestrator = TrinitySchemaOrchestrator()

    # Act
    files = orchestrator.generate_schema(entities)

    # Assert
    assert len(files) >= 8  # 2 entities × (tb + tv + helpers + vector + fulltext)

    # Check cross-entity references work
    all_content = "\n".join(f.content for f in files)
    assert "tb_contact" in all_content
    assert "tb_company" in all_content
    assert "tv_contact" in all_content
    assert "tv_company" in all_content
    assert "contact_pk" in all_content
    assert "company_id" in all_content