# E-Commerce Product Entity Example
# This example demonstrates a complete product catalog entity with variants,
# inventory tracking, and search optimization.

entity: Product
namespace: ecommerce
description: "Product catalog with variants, inventory, and pricing"

patterns:
  - state_machine:
      states: [draft, active, discontinued, out_of_stock]
      initial_state: draft
      transitions:
        publish: { from: draft, to: active }
        discontinue: { from: [active, out_of_stock], to: discontinued }
        restock: { from: out_of_stock, to: active }
  - audit_trail:
      track_versions: true
  - soft_delete
  - search_optimization:
      full_text_fields: [name, description, tags]
      weighted_search: true
      facets: [category, brand, price_range]
  - computed_fields:
      fields:
        - name: total_inventory
          expression: "SELECT COALESCE(SUM(quantity), 0) FROM ecommerce.tb_product_variant WHERE product_id = id AND deleted_at IS NULL"
          update_triggers: ["ecommerce.tb_product_variant.quantity"]
        - name: average_rating
          expression: "SELECT COALESCE(AVG(rating), 0) FROM ecommerce.tb_product_review WHERE product_id = id AND status = 'approved'"

fields:
  # Basic product information
  name:
    type: text
    required: true
    description: "Product name"

  description:
    type: text
    description: "Detailed product description"

  short_description:
    type: text
    description: "Brief product description for listings"

  sku:
    type: text
    required: true
    unique: true
    description: "Stock Keeping Unit - unique product identifier"

  # Categorization
  category:
    type: text
    required: true
    indexed: true
    description: "Product category"

  subcategory:
    type: text
    indexed: true
    description: "Product subcategory"

  brand:
    type: text
    indexed: true
    description: "Product brand or manufacturer"

  tags:
    type: text[]
    description: "Product tags for search and filtering"

  # Pricing
  base_price:
    type: numeric(10,2)
    required: true
    min: 0
    description: "Base product price"

  sale_price:
    type: numeric(10,2)
    min: 0
    description: "Sale/discounted price (null if not on sale)"

  cost_price:
    type: numeric(10,2)
    description: "Product cost for margin calculations"

  # Product details
  weight_grams:
    type: integer
    min: 0
    description: "Product weight in grams"

  dimensions_length_cm:
    type: numeric(8,2)
    min: 0
    description: "Length in centimeters"

  dimensions_width_cm:
    type: numeric(8,2)
    min: 0
    description: "Width in centimeters"

  dimensions_height_cm:
    type: numeric(8,2)
    min: 0
    description: "Height in centimeters"

  # Media
  main_image_url:
    type: text
    description: "URL of main product image"

  additional_images:
    type: text[]
    description: "URLs of additional product images"

  # SEO and marketing
  seo_title:
    type: text
    description: "SEO-optimized title"

  seo_description:
    type: text
    description: "SEO meta description"

  seo_keywords:
    type: text[]
    description: "SEO keywords"

  # Product features
  is_featured:
    type: boolean
    default: false
    description: "Featured product flag"

  is_bestseller:
    type: boolean
    default: false
    description: "Bestseller flag (computed)"

  requires_shipping:
    type: boolean
    default: true
    description: "Whether this product requires shipping"

  is_digital:
    type: boolean
    default: false
    description: "Digital product (no shipping required)"

  # Inventory settings
  track_inventory:
    type: boolean
    default: true
    description: "Whether to track inventory for this product"

  allow_backorders:
    type: boolean
    default: false
    description: "Allow backorders when out of stock"

  low_stock_threshold:
    type: integer
    default: 5
    min: 0
    description: "Low stock alert threshold"

  # Variant support
  has_variants:
    type: boolean
    default: false
    description: "Whether this product has variants"

  variant_options:
    type: jsonb
    description: "Variant option definitions (size, color, etc.)"

actions:
  - name: create_product
    description: "Create a new product with validation"
    parameters:
      name: text
      description: text
      sku: text
      category: text
      base_price: numeric
      track_inventory: boolean
    steps:
      - type: validate
        condition: "name IS NOT NULL AND length(trim(name)) > 0"
        error_message: "Product name is required"

      - type: validate
        condition: "sku IS NOT NULL AND length(trim(sku)) > 0"
        error_message: "SKU is required"

      - type: validate
        condition: "{{ base_price }} > 0"
        error_message: "Base price must be greater than 0"

      - type: duplicate_check
        table: ecommerce.tb_product
        fields: [sku]
        error_message: "Product with this SKU already exists"

      - type: insert
        table: ecommerce.tb_product
        data:
          name: "{{ name }}"
          description: "{{ description }}"
          sku: "{{ sku }}"
          category: "{{ category }}"
          base_price: "{{ base_price }}"
          track_inventory: "COALESCE({{ track_inventory }}, true)"
          state: "'draft'"

  - name: update_product
    description: "Update product information"
    parameters:
      product_id: uuid
      name: text
      description: text
      base_price: numeric
      sale_price: numeric
      category: text
      tags: text[]
    steps:
      - type: validate
        condition: "EXISTS (SELECT 1 FROM ecommerce.tb_product WHERE id = {{ product_id }} AND deleted_at IS NULL)"
        error_message: "Product not found"

      - type: validate
        condition: "{{ base_price }} > 0"
        error_message: "Base price must be greater than 0"

      - type: validate
        condition: "{{ sale_price }} IS NULL OR {{ sale_price }} > 0"
        error_message: "Sale price must be greater than 0 if provided"

      - type: validate
        condition: "{{ sale_price }} IS NULL OR {{ sale_price }} < {{ base_price }}"
        error_message: "Sale price must be less than base price"

      - type: update
        table: ecommerce.tb_product
        data:
          name: "{{ name }}"
          description: "{{ description }}"
          base_price: "{{ base_price }}"
          sale_price: "{{ sale_price }}"
          category: "{{ category }}"
          tags: "{{ tags }}"
        where: "id = {{ product_id }}"

  - name: publish_product
    description: "Publish a product to make it available for purchase"
    parameters:
      product_id: uuid
    steps:
      - type: validate
        condition: "EXISTS (SELECT 1 FROM ecommerce.tb_product WHERE id = {{ product_id }} AND state = 'draft' AND deleted_at IS NULL)"
        error_message: "Product not found or not in draft state"

      - type: validate
        condition: "EXISTS (SELECT 1 FROM ecommerce.tb_product WHERE id = {{ product_id }} AND total_inventory > 0)"
        error_message: "Cannot publish product with no inventory"

      - type: update
        table: ecommerce.tb_product
        data:
          state: "'active'"
          published_at: "NOW()"
        where: "id = {{ product_id }}"

  - name: update_inventory
    description: "Update product inventory levels"
    parameters:
      product_id: uuid
      adjustment: integer
      reason: text
    steps:
      - type: validate
        condition: "EXISTS (SELECT 1 FROM ecommerce.tb_product WHERE id = {{ product_id }} AND track_inventory = true AND deleted_at IS NULL)"
        error_message: "Product not found or inventory not tracked"

      - type: select
        query: "SELECT total_inventory FROM ecommerce.tb_product WHERE id = {{ product_id }}"
        result_variable: current_inventory

      - type: assign
        variable_name: new_inventory
        expression: "GREATEST(0, current_inventory.total_inventory + {{ adjustment }})"

      - type: update
        table: ecommerce.tb_product
        data:
          total_inventory: new_inventory
          state: "CASE WHEN new_inventory = 0 THEN 'out_of_stock' ELSE state END"
        where: "id = {{ product_id }}"

      - type: insert
        table: ecommerce.tb_inventory_log
        data:
          product_id: "{{ product_id }}"
          adjustment: "{{ adjustment }}"
          previous_quantity: current_inventory.total_inventory
          new_quantity: new_inventory
          reason: "{{ reason }}"

  - name: add_product_variant
    description: "Add a product variant (size, color, etc.)"
    parameters:
      product_id: uuid
      variant_name: text
      sku: text
      price_adjustment: numeric
      options: jsonb
      initial_stock: integer
    steps:
      - type: validate
        condition: "EXISTS (SELECT 1 FROM ecommerce.tb_product WHERE id = {{ product_id }} AND has_variants = true AND deleted_at IS NULL)"
        error_message: "Product not found or does not support variants"

      - type: duplicate_check
        table: ecommerce.tb_product_variant
        fields: [product_id, sku]
        error_message: "Variant with this SKU already exists for this product"

      - type: insert
        table: ecommerce.tb_product_variant
        data:
          product_id: "{{ product_id }}"
          variant_name: "{{ variant_name }}"
          sku: "{{ sku }}"
          price_adjustment: "{{ price_adjustment }}"
          options: "{{ options }}"
          quantity: "{{ initial_stock }}"

  - name: search_products
    description: "Search products with advanced filtering"
    parameters:
      query: text
      category: text
      min_price: numeric
      max_price: numeric
      in_stock_only: boolean
      sort_by: text
      sort_order: text
      limit: integer
      offset: integer
    steps:
      - type: assign
        variable_name: search_limit
        expression: "COALESCE({{ limit }}, 20)"

      - type: assign
        variable_name: search_offset
        expression: "COALESCE({{ offset }}, 0)"

      - type: assign
        variable_name: sort_column
        expression: |
          CASE {{ sort_by }}
            WHEN 'price' THEN 'base_price'
            WHEN 'name' THEN 'name'
            WHEN 'rating' THEN 'average_rating'
            WHEN 'newest' THEN 'created_at'
            ELSE 'created_at'
          END

      - type: assign
        variable_name: sort_direction
        expression: "CASE WHEN {{ sort_order }} = 'desc' THEN 'DESC' ELSE 'ASC' END"

      - type: select
        query: |
          SELECT p.*,
                 ts_rank_cd(p.search_vector, plainto_tsquery('english', COALESCE({{ query }}, ''))) as search_rank
          FROM ecommerce.tb_product p
          WHERE p.deleted_at IS NULL
            AND p.state = 'active'
            AND ({{ query }} IS NULL OR p.search_vector @@ plainto_tsquery('english', {{ query }}))
            AND ({{ category }} IS NULL OR p.category = {{ category }})
            AND ({{ min_price }} IS NULL OR p.base_price >= {{ min_price }})
            AND ({{ max_price }} IS NULL OR p.base_price <= {{ max_price }})
            AND ({{ in_stock_only }} IS NULL OR {{ in_stock_only }} = false OR p.total_inventory > 0)
          ORDER BY
            CASE WHEN {{ query }} IS NOT NULL THEN search_rank ELSE 0 END DESC,
            {{ sort_column }} {{ sort_direction }}
          LIMIT {{ search_limit }} OFFSET {{ search_offset }}
        result_variable: products

      - type: return
        expression: jsonb_build_object(
          'products', products,
          'total_count', (SELECT count(*) FROM ecommerce.tb_product WHERE deleted_at IS NULL AND state = 'active'),
          'query', {{ query }},
          'filters', jsonb_build_object(
            'category', {{ category }},
            'min_price', {{ min_price }},
            'max_price', {{ max_price }},
            'in_stock_only', {{ in_stock_only }}
          )
        )

  - name: get_product_details
    description: "Get complete product details including variants and reviews"
    parameters:
      product_id: uuid
    steps:
      - type: select
        query: |
          SELECT p.*,
                 jsonb_agg(DISTINCT pv.*) as variants,
                 jsonb_agg(DISTINCT pr.*) as reviews
          FROM ecommerce.tb_product p
          LEFT JOIN ecommerce.tb_product_variant pv ON p.id = pv.product_id AND pv.deleted_at IS NULL
          LEFT JOIN ecommerce.tb_product_review pr ON p.id = pr.product_id AND pr.status = 'approved'
          WHERE p.id = {{ product_id }} AND p.deleted_at IS NULL
          GROUP BY p.id
        result_variable: product_details

      - type: return
        expression: product_details

  - name: apply_discount
    description: "Apply a percentage discount to a product"
    parameters:
      product_id: uuid
      discount_percentage: numeric
      start_date: timestamptz
      end_date: timestamptz
    steps:
      - type: validate
        condition: "{{ discount_percentage }} > 0 AND {{ discount_percentage }} < 100"
        error_message: "Discount percentage must be between 1 and 99"

      - type: validate
        condition: "{{ start_date }} < {{ end_date }}"
        error_message: "Start date must be before end date"

      - type: update
        table: ecommerce.tb_product
        data:
          sale_price: "base_price * (1 - {{ discount_percentage }} / 100)"
          discount_start: "{{ start_date }}"
          discount_end: "{{ end_date }}"
        where: "id = {{ product_id }}"

# Related tables that would be created:
# - tb_product_variant: Product variants (size, color, etc.)
# - tb_product_review: Customer reviews and ratings
# - tb_inventory_log: Inventory change history
# - tb_product_category: Category hierarchy
# - tb_product_image: Product images and media

# This example demonstrates:
# - Complex product catalog management
# - Variant support for configurable products
# - Inventory tracking and management
# - Advanced search with faceting
# - Pricing and discount management
# - State management for product lifecycle
# - Computed fields for aggregations
# - Full-text search optimization