"""Round-trip validation tests for reverse engineering."""

from click.testing import CliRunner

from cli.reverse_schema import reverse_schema


class TestRoundTripValidation:
    """Test round-trip validation (SQL → YAML → SQL)."""

    def test_reverse_and_generate_roundtrip(self, tmp_path):
        """Reverse engineer SQL → YAML, then validate the YAML can be processed."""
        original_sql = """
        CREATE TABLE catalog.tb_manufacturer (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pk_manufacturer UUID DEFAULT gen_random_uuid() NOT NULL,
            identifier TEXT NOT NULL,
            name TEXT,
            abbreviation CHAR(2) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT tb_manufacturer_identifier_key UNIQUE (identifier),
            CONSTRAINT tb_manufacturer_pk_manufacturer_key UNIQUE (pk_manufacturer)
        );
        """

        sql_file = tmp_path / "manufacturer.sql"
        sql_file.write_text(original_sql)

        yaml_dir = tmp_path / "yaml_output"
        yaml_dir.mkdir()

        # Step 1: SQL → YAML (reverse engineer)
        runner = CliRunner()
        result = runner.invoke(reverse_schema, [str(sql_file), "--output-dir", str(yaml_dir)])

        assert result.exit_code == 0

        yaml_path = yaml_dir / "catalog" / "manufacturer.yaml"
        assert yaml_path.exists()

        yaml_content = yaml_path.read_text()
        assert "entity: Manufacturer" in yaml_content
        assert "identifier: text!" in yaml_content
        assert "name: text" in yaml_content
        assert "abbreviation: char(2)!" in yaml_content

        # Step 2: Validate YAML structure (we can't easily test full round-trip
        # to SQL generation without the generate command, but we can validate
        # the YAML is well-formed and contains expected patterns)

        import yaml as yaml_lib

        parsed_yaml = yaml_lib.safe_load(yaml_content)

        # Validate required fields
        assert parsed_yaml["entity"] == "Manufacturer"
        assert parsed_yaml["schema"] == "catalog"
        assert "fields" in parsed_yaml
        assert "patterns" in parsed_yaml
        assert "_metadata" in parsed_yaml

        # Validate business fields are present and technical fields excluded
        fields = parsed_yaml["fields"]
        assert "identifier" in fields
        assert "name" in fields
        assert "abbreviation" in fields

        # Technical fields should not be in the final YAML
        assert "id" not in fields
        assert "pk_manufacturer" not in fields
        assert "created_at" not in fields
        assert "updated_at" not in fields

        # Validate patterns detected
        patterns = parsed_yaml["patterns"]
        assert "trinity" in patterns
        # Note: audit_trail not detected with only 2 fields (created_at, updated_at)

        # Validate metadata
        metadata = parsed_yaml["_metadata"]
        assert metadata["generated_by"] == "specql-reverse-schema"
        assert "generated_at" in metadata
        assert metadata["confidence"] > 0
