"""Integration tests for reverse-schema CLI command."""

from click.testing import CliRunner

from cli.reverse_schema import reverse_schema


class TestReverseSchemaCLI:
    """Integration tests for the reverse-schema CLI command."""

    def test_reverse_schema_command(self, tmp_path):
        """Test basic reverse-schema CLI command."""
        sql_file = tmp_path / "manufacturer.sql"
        sql_file.write_text("""
        CREATE TABLE catalog.tb_manufacturer (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pk_manufacturer UUID DEFAULT gen_random_uuid() NOT NULL,
            identifier TEXT NOT NULL,
            name TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now()
        );
        """)

        output_dir = tmp_path / "entities"

        runner = CliRunner()
        result = runner.invoke(reverse_schema, [str(sql_file), "--output-dir", str(output_dir)])

        assert result.exit_code == 0
        assert (output_dir / "catalog" / "manufacturer.yaml").exists()

        yaml_content = (output_dir / "catalog" / "manufacturer.yaml").read_text()
        assert "entity: Manufacturer" in yaml_content
        assert "schema: catalog" in yaml_content
        assert "identifier: text!" in yaml_content
        assert "name: text!" in yaml_content
        assert "trinity" in yaml_content
        # Note: audit_trail not detected with only 2 fields (created_at, updated_at)

    def test_batch_process_with_translations(self, tmp_path):
        """Test batch processing with translation table detection."""
        # Create main table
        main_sql = tmp_path / "manufacturer.sql"
        main_sql.write_text("""
        CREATE TABLE catalog.tb_manufacturer (
            pk_manufacturer UUID PRIMARY KEY,
            name TEXT,
            color_name TEXT
        );
        """)

        # Create translation table
        translation_sql = tmp_path / "manufacturer_translation.sql"
        translation_sql.write_text("""
        CREATE TABLE catalog.tb_manufacturer_translation (
            fk_manufacturer UUID NOT NULL,
            locale TEXT NOT NULL,
            name TEXT,
            color_name TEXT,
            PRIMARY KEY (fk_manufacturer, locale)
        );
        """)

        output_dir = tmp_path / "entities"

        runner = CliRunner()
        result = runner.invoke(
            reverse_schema,
            [
                str(main_sql),
                str(translation_sql),
                "--output-dir",
                str(output_dir),
                "--merge-translations",
            ],
        )

        assert result.exit_code == 0

        # Should create single merged entity file
        yaml_path = output_dir / "catalog" / "manufacturer.yaml"
        assert yaml_path.exists()

        yaml_content = yaml_path.read_text()
        assert "entity: Manufacturer" in yaml_content
        assert "translations:" in yaml_content
        assert "locale: ref(Locale)" in yaml_content
        assert "name: text" in yaml_content
        assert "color_name: text" in yaml_content
