"""
Documentation generators for SpecQL entities.

Generates Markdown, HTML, or JSON documentation from parsed entities.
"""

from pathlib import Path
from typing import Any


class DocsGenerator:
    """Generate documentation from SpecQL entities."""

    def __init__(self, output_format: str = "markdown", include_examples: bool = True):
        self.output_format = output_format
        self.include_examples = include_examples

    def generate(self, entities: list[tuple[Any, str]], output_path: Path) -> list[str]:
        """Generate all documentation files."""
        # Use format-specific generator
        if self.output_format == "json":
            generator = JSONDocsGenerator()
            return generator.generate(entities, output_path)
        elif self.output_format == "html":
            generator = HTMLDocsGenerator()
            return generator.generate(entities, output_path)
        else:  # markdown (default)
            return self._generate_markdown(entities, output_path)

    def _generate_markdown(self, entities: list[tuple[Any, str]], output_path: Path) -> list[str]:
        """Generate markdown documentation files."""
        generated = []

        # Generate index
        index_content = self._generate_index(entities)
        index_file = output_path / "index.md"
        index_file.write_text(index_content)
        generated.append("index.md")

        # Generate entity docs
        for entity, source_file in entities:
            entity_content = self._generate_entity_doc(entity, source_file)
            entity_file = output_path / "entities" / f"{entity.name.lower()}.md"
            entity_file.write_text(entity_content)
            generated.append(f"entities/{entity.name.lower()}.md")

        # Generate mutations docs
        mutations_generated = self._generate_mutations_doc(entities, output_path)
        if mutations_generated:
            generated.append("mutations/mutations.md")

        return generated

    def _generate_index(self, entities: list[tuple[Any, str]]) -> str:
        """Generate index.md with navigation."""
        lines = [
            "# SpecQL Documentation",
            "",
            "Auto-generated documentation from SpecQL YAML definitions.",
            "",
            "## Entities",
            "",
        ]

        for entity, source_file in entities:
            lines.append(
                f"- [{entity.name}](entities/{entity.name.lower()}.md) - {entity.description or 'No description'}"
            )

        # Add mutations link if any entities have actions
        has_actions = any(entity.actions for entity, _ in entities)
        if has_actions:
            lines.extend(
                [
                    "",
                    "## API Reference",
                    "",
                    "- [Mutations](mutations/mutations.md) - GraphQL mutation API reference",
                ]
            )

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by SpecQL*",
            ]
        )

        return "\n".join(lines)

    def _generate_entity_doc(self, entity, source_file: str) -> str:
        """Generate entity-specific documentation."""
        lines = [
            f"# {entity.name}",
            "",
        ]

        # Description
        if entity.description:
            lines.extend([entity.description, ""])

        # Metadata
        lines.extend(
            [
                "## Overview",
                "",
                f"- **Schema**: `{entity.schema}`",
                f"- **Table**: `tb_{entity.name.lower()}`",
                f"- **Source**: `{source_file}`",
                "",
            ]
        )

        # Fields table
        lines.extend(
            [
                "## Fields",
                "",
                "| Field | Type | Required | Description |",
                "|-------|------|----------|-------------|",
            ]
        )

        for field_name, field in entity.fields.items():
            field_type = self._format_field_type(field)
            required = "Yes" if not field.nullable else "No"
            description = field.description or "-"
            lines.append(f"| `{field_name}` | {field_type} | {required} | {description} |")

        lines.append("")

        # Actions section
        if entity.actions:
            lines.extend(
                [
                    "## Actions",
                    "",
                ]
            )

            for action in entity.actions:
                lines.extend(
                    [
                        f"### {action.name}",
                        "",
                        action.description or "No description provided.",
                        "",
                    ]
                )

        # Footer
        lines.extend(
            [
                "---",
                "",
                "*Generated by SpecQL*",
            ]
        )

        return "\n".join(lines)

    def _format_field_type(self, field) -> str:
        """Format field type for display."""
        type_name = field.type_name

        if field.reference_entity:
            return f"`ref({field.reference_entity})`"
        if field.values:
            values = ", ".join(field.values[:3])
            if len(field.values) > 3:
                values += ", ..."
            return f"`enum({values})`"
        if field.item_type:
            return f"`list({field.item_type})`"

        return f"`{type_name}`"

    def _generate_mutations_doc(self, entities: list[tuple[Any, str]], output_path: Path) -> bool:
        """Generate mutations documentation using MutationDocsGenerator."""
        try:
            from generators.frontend.mutation_docs_generator import MutationDocsGenerator

            mutations_dir = output_path / "mutations"
            generator = MutationDocsGenerator(mutations_dir)
            entity_list = [entity for entity, _ in entities]
            generator.generate_docs(entity_list)

            # Check if the file was generated
            mutations_file = mutations_dir / "mutations.md"
            return mutations_file.exists()
        except (ImportError, Exception):
            # Fallback to simple mutation list
            mutations_content = self._generate_simple_mutations_doc(entities)
            mutations_file = output_path / "mutations" / "mutations.md"
            mutations_file.parent.mkdir(parents=True, exist_ok=True)
            mutations_file.write_text(mutations_content)
            return True

    def _generate_simple_mutations_doc(self, entities: list[tuple[Any, str]]) -> str:
        """Simple mutations documentation fallback."""
        lines = [
            "# Mutations Reference",
            "",
            "GraphQL mutations generated from SpecQL actions.",
            "",
        ]

        for entity, source_file in entities:
            if not entity.actions:
                continue

            lines.extend(
                [
                    f"## {entity.name}",
                    "",
                ]
            )

            for action in entity.actions:
                lines.extend(
                    [
                        f"### `{action.name}`",
                        "",
                        action.description or "No description.",
                        "",
                    ]
                )

        return "\n".join(lines)


class JSONDocsGenerator(DocsGenerator):
    """Generate JSON documentation."""

    def generate(self, entities: list[tuple[Any, str]], output_path: Path) -> list[str]:
        """Generate JSON documentation."""
        import json

        docs_data = {
            "entities": [],
            "generated_by": "specql",
            "format": "json",
        }

        for entity, source_file in entities:
            entity_data = {
                "name": entity.name,
                "schema": entity.schema,
                "description": entity.description,
                "fields": {
                    name: {
                        "type": field.type_name,
                        "nullable": field.nullable,
                        "description": field.description,
                        "reference": field.reference_entity,
                        "enum_values": list(field.values) if field.values else None,
                        "item_type": field.item_type,
                    }
                    for name, field in entity.fields.items()
                },
                "actions": [
                    {"name": a.name, "description": a.description} for a in (entity.actions or [])
                ],
                "source_file": source_file,
            }
            docs_data["entities"].append(entity_data)

        output_file = output_path / "docs.json"
        output_file.write_text(json.dumps(docs_data, indent=2))
        return ["docs.json"]


class HTMLDocsGenerator(DocsGenerator):
    """Generate HTML documentation."""

    def generate(self, entities: list[tuple[Any, str]], output_path: Path) -> list[str]:
        """Generate HTML documentation."""
        generated = []

        # Generate index.html
        index_html = self._generate_index_html(entities)
        index_file = output_path / "index.html"
        index_file.write_text(index_html)
        generated.append("index.html")

        # Generate entity HTML files
        for entity, source_file in entities:
            entity_html = self._generate_entity_html(entity, source_file)
            entity_file = output_path / f"{entity.name.lower()}.html"
            entity_file.write_text(entity_html)
            generated.append(f"{entity.name.lower()}.html")

        return generated

    def _generate_index_html(self, entities: list[tuple[Any, str]]) -> str:
        """Generate index.html with navigation."""
        css = """
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        .entity-list { list-style: none; padding: 0; }
        .entity-list li { margin: 10px 0; padding: 15px; background: #f8f9fa; border-radius: 5px; border-left: 4px solid #3498db; }
        .entity-list a { text-decoration: none; color: #2c3e50; font-weight: 500; }
        .entity-list a:hover { color: #3498db; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1; color: #7f8c8d; font-size: 0.9em; }
        """

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SpecQL Documentation</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
        <h1>SpecQL Documentation</h1>
        <p>Auto-generated documentation from SpecQL YAML definitions.</p>

        <h2>Entities</h2>
        <ul class="entity-list">
"""

        for entity, source_file in entities:
            html += f'            <li><a href="{entity.name.lower()}.html">{entity.name}</a> - {entity.description or "No description"}</li>\n'

        html += """        </ul>

        <div class="footer">
            <p><em>Generated by SpecQL</em></p>
        </div>
    </div>
</body>
</html>"""

        return html

    def _generate_entity_html(self, entity, source_file: str) -> str:
        """Generate entity-specific HTML documentation."""
        css = """
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        .overview { background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .overview dt { font-weight: bold; color: #2c3e50; }
        .overview dd { margin: 5px 0 15px 0; color: #555; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ecf0f1; }
        th { background: #3498db; color: white; font-weight: 500; }
        tr:nth-child(even) { background: #f8f9fa; }
        .code { font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace; background: #f8f9fa; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
        .actions { margin: 20px 0; }
        .action { background: #e8f4fd; padding: 15px; border-radius: 5px; margin: 10px 0; border-left: 4px solid #3498db; }
        .action h3 { margin: 0 0 10px 0; color: #2c3e50; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1; color: #7f8c8d; font-size: 0.9em; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
        """

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{entity.name} - SpecQL Documentation</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
        <h1>{entity.name}</h1>
"""

        if entity.description:
            html += f"        <p>{entity.description}</p>\n"

        html += f"""
        <h2>Overview</h2>
        <dl class="overview">
            <dt>Schema</dt>
            <dd><span class="code">{entity.schema}</span></dd>
            <dt>Table</dt>
            <dd><span class="code">tb_{entity.name.lower()}</span></dd>
            <dt>Source</dt>
            <dd><span class="code">{source_file}</span></dd>
        </dl>

        <h2>Fields</h2>
        <table>
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Type</th>
                    <th>Required</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
"""

        for field_name, field in entity.fields.items():
            field_type = self._format_field_type(field)
            required = "Yes" if not field.nullable else "No"
            description = field.description or "-"
            html += f"""                <tr>
                    <td><span class="code">{field_name}</span></td>
                    <td><span class="code">{field_type}</span></td>
                    <td>{required}</td>
                    <td>{description}</td>
                </tr>
"""

        html += """            </tbody>
        </table>
"""

        if entity.actions:
            html += """
        <h2>Actions</h2>
        <div class="actions">
"""
            for action in entity.actions:
                html += f"""            <div class="action">
                <h3><span class="code">{action.name}</span></h3>
                <p>{action.description or "No description provided."}</p>
            </div>
"""

            html += """        </div>
"""

        html += """
        <div class="footer">
            <p><em>Generated by SpecQL</em></p>
            <p><a href="index.html">← Back to Index</a></p>
        </div>
    </div>
</body>
</html>"""

        return html
