-- ============================================================================
-- Table: public.tb_booker
-- ============================================================================
-- [Table: BOO | Booker entity]
-- ============================================================================

CREATE TABLE public.tb_booker (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_booker INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    group_size INTEGER NOT NULL,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_booker_id_key UNIQUE (id)
    ,CONSTRAINT chk_tb_booker_email_pattern CHECK (email ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE public.tb_booker IS
'Booker entity.

@fraiseql:type
trinity: true
';

-- Trinity Pattern columns
COMMENT ON COLUMN public.tb_booker.pk_booker IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN public.tb_booker.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN public.tb_booker.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN public.tb_booker.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN public.tb_booker.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN public.tb_booker.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN public.tb_booker.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN public.tb_booker.deleted_by IS 'User or system who deleted the record.';