-- ============================================================================
-- Table: crm.tb_company
-- ============================================================================
-- [Table: COM | Company information]
-- ============================================================================

CREATE TABLE crm.tb_company (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_company INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Multi-Tenancy: Denormalized from JWT (CRITICAL for security)
    -- ========================================================================
    tenant_id UUID NOT NULL,

    -- ========================================================================
    -- Multi-Tenancy: Optional business FK to organization
    -- ========================================================================
    -- Note: Only add fk_organization if entity belongs to specific org unit
    -- (not just tenant isolation). Comment out if not needed.
    -- fk_organization INTEGER,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    name TEXT,
    industry TEXT,
    website TEXT,
    size TEXT,
    description TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_company_id_key UNIQUE (id)
    ,CONSTRAINT chk_tb_company_size_enum CHECK (size IN ('small', 'medium', 'large', 'enterprise')));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================-- ============================================================================
-- Multi-Tenancy Indexes (CRITICAL for performance & RLS)
-- ============================================================================
CREATE INDEX idx_tb_company_tenant ON crm.tb_company(tenant_id);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE crm.tb_company IS
'Company information.

@fraiseql:type
trinity: true
';

-- Trinity Pattern columns
COMMENT ON COLUMN crm.tb_company.pk_company IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN crm.tb_company.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Multi-Tenancy columns
COMMENT ON COLUMN crm.tb_company.tenant_id IS 'Denormalized tenant identifier from JWT token (security context).';
-- COMMENT ON COLUMN crm.tb_company.fk_organization IS 'Optional business FK to organization unit (uncomment if needed).';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN crm.tb_company.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN crm.tb_company.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN crm.tb_company.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN crm.tb_company.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN crm.tb_company.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN crm.tb_company.deleted_by IS 'User or system who deleted the record.';