-- ============================================================================
-- Table: catalog.tb_locale
-- ============================================================================
-- [Table: LOC | IETF BCP 47 locale codes (language + region) for localization]
-- ============================================================================

CREATE TABLE catalog.tb_locale (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_locale INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    flag_emoji TEXT,
    decimal_separator TEXT,
    grouping_separator TEXT,
    numeric_pattern TEXT,
    currency_symbol_position TEXT,
    currency_pattern TEXT,
    date_format TEXT,
    time_format TEXT,
    first_day_of_week TEXT,
    is_rtl BOOLEAN,
    is_default BOOLEAN,
    is_active BOOLEAN,
    sort_order INTEGER,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    fk_language INTEGER NOT NULL,

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_locale_id_key UNIQUE (id)
    ,CONSTRAINT chk_tb_locale_currency_symbol_position_enum CHECK (currency_symbol_position IN ('before', 'after'))
    ,CONSTRAINT chk_tb_locale_first_day_of_week_enum CHECK (first_day_of_week IN ('sunday', 'monday')));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
ALTER TABLE ONLY catalog.tb_locale
    ADD CONSTRAINT tb_locale_fk_language_fkey
    FOREIGN KEY (fk_language) REFERENCES catalog.tb_language(pk_language);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE catalog.tb_locale IS
'IETF BCP 47 locale codes (language + region) for localization.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN catalog.tb_locale.pk_locale IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN catalog.tb_locale.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN catalog.tb_locale.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN catalog.tb_locale.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN catalog.tb_locale.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN catalog.tb_locale.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN catalog.tb_locale.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN catalog.tb_locale.deleted_by IS 'User or system who deleted the record.';