-- ============================================================================
-- Table: tenant.tb_machine
-- ============================================================================
-- [Table: 014511 | [014511 | Write-Side.Dimensions.Material.Machine]
Represents a physical printing device.
]
-- ============================================================================

CREATE TABLE tenant.tb_machine (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_machine INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Multi-Tenancy: Denormalized from JWT (CRITICAL for security)
    -- ========================================================================
    tenant_id UUID NOT NULL,

    -- ========================================================================
    -- Multi-Tenancy: Optional business FK to organization
    -- ========================================================================
    -- Note: Only add fk_organization if entity belongs to specific org unit
    -- (not just tenant isolation). Comment out if not needed.
    -- fk_organization INTEGER,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    code TEXT NOT NULL,
    serial_number TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_machine_id_key UNIQUE (id));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================-- ============================================================================
-- Multi-Tenancy Indexes (CRITICAL for performance & RLS)
-- ============================================================================
CREATE INDEX idx_tb_machine_tenant ON tenant.tb_machine(tenant_id);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE tenant.tb_machine IS
'[014511 | Write-Side.Dimensions.Material.Machine]
Represents a physical printing device.
.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN tenant.tb_machine.pk_machine IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN tenant.tb_machine.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Multi-Tenancy columns
COMMENT ON COLUMN tenant.tb_machine.tenant_id IS 'Denormalized tenant identifier from JWT token (security context).';
-- COMMENT ON COLUMN tenant.tb_machine.fk_organization IS 'Optional business FK to organization unit (uncomment if needed).';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN tenant.tb_machine.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN tenant.tb_machine.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN tenant.tb_machine.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN tenant.tb_machine.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN tenant.tb_machine.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN tenant.tb_machine.deleted_by IS 'User or system who deleted the record.';