-- ============================================================================
-- Table: catalog.tb_manufacturerrange
-- ============================================================================
-- [Table: 013212 | Product ranges from manufacturers]
-- ============================================================================

CREATE TABLE catalog.tb_manufacturerrange (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_manufacturerrange INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    name TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    fk_manufacturer INTEGER,

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_manufacturerrange_id_key UNIQUE (id));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
ALTER TABLE ONLY catalog.tb_manufacturerrange
    ADD CONSTRAINT tb_manufacturerrange_fk_manufacturer_fkey
    FOREIGN KEY (fk_manufacturer) REFERENCES catalog.tb_manufacturer(pk_manufacturer);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE catalog.tb_manufacturerrange IS
'Product ranges from manufacturers.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN catalog.tb_manufacturerrange.pk_manufacturerrange IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN catalog.tb_manufacturerrange.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN catalog.tb_manufacturerrange.deleted_by IS 'User or system who deleted the record.';