-- ============================================================================
-- Table: sales.tb_order
-- ============================================================================
-- [Table: ORD | Order entity]
-- ============================================================================

CREATE TABLE sales.tb_order (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_order INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    status TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_order_id_key UNIQUE (id));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE sales.tb_order IS
'Order entity.

@fraiseql:type
trinity: true
';

-- Trinity Pattern columns
COMMENT ON COLUMN sales.tb_order.pk_order IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN sales.tb_order.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN sales.tb_order.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN sales.tb_order.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN sales.tb_order.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN sales.tb_order.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN sales.tb_order.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN sales.tb_order.deleted_by IS 'User or system who deleted the record.';