-- ============================================================================
-- Table: catalog.tb_product
-- ============================================================================
-- [Table: PRO | Product entity]
-- ============================================================================

CREATE TABLE catalog.tb_product (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_product INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    product_code TEXT,
    name TEXT,
    price TEXT,
    description TEXT,
    version_number INTEGER NOT NULL,
    is_current BOOLEAN NOT NULL,
    effective_date TIMESTAMPTZ NOT NULL,
    expiry_date TIMESTAMPTZ,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_product_id_key UNIQUE (id));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================-- ============================================================================
-- Pattern Indexes
-- ============================================================================
CREATE INDEX idx_product_current_nk ON catalog.tb_product (product_code, is_current);-- ============================================================================
-- Pattern Indexes
-- ============================================================================
CREATE INDEX idx_product_temporal ON catalog.tb_product (product_code, effective_date, expiry_date);-- ============================================================================
-- Pattern Indexes
-- ============================================================================
CREATE INDEX idx_product_version_order ON catalog.tb_product (product_code, version_number);-- ============================================================================
-- SCD Function
-- ============================================================================
CREATE OR REPLACE FUNCTION create_new_version_product(
natural_key_values jsonb, new_data jsonb, effective_at timestamptz DEFAULT now()
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  v_old_id uuid;
  v_new_id uuid;
  v_next_version integer;
BEGIN
  -- Get current version ID and next version number
  SELECT id, version_number + 1
  INTO v_old_id, v_next_version
  FROM catalog.tb_product
  WHERE product_code = (natural_key_values->>'product_code')::TEXT
    AND is_current = true;

  IF v_old_id IS NULL THEN
    RAISE EXCEPTION 'No current version found for given natural key';
  END IF;

  -- Expire current version
  UPDATE catalog.tb_product
  SET
    is_current = false,
    expiry_date = effective_at,
    updated_at = now(),
    updated_by = current_setting('app.current_user_id', true)::uuid
  WHERE id = v_old_id;

  -- Insert new version
  INSERT INTO catalog.tb_product (
    product_code, name, price, description,
    version_number,
    is_current,
    effective_date,
    expiry_date
  )
  SELECT
    (new_data->>'product_code')::TEXT, (new_data->>'name')::TEXT, (new_data->>'price')::TEXT, (new_data->>'description')::TEXT,
    v_next_version,
    true,
    effective_at,
    NULL
  FROM jsonb_populate_record(NULL::catalog.tb_product, new_data)
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;-- ============================================================================
-- SCD Function
-- ============================================================================
CREATE OR REPLACE FUNCTION get_current_version_product(
natural_key_values jsonb
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
SELECT id
FROM catalog.tb_product
WHERE product_code = (natural_key_values->>'product_code')::TEXT
  AND is_current = true;
$$;-- ============================================================================
-- SCD Function
-- ============================================================================
CREATE OR REPLACE FUNCTION get_version_at_time_product(
natural_key_values jsonb, as_of_time timestamptz
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
SELECT id
FROM catalog.tb_product
WHERE product_code = (natural_key_values->>'product_code')::TEXT
  AND effective_date <= as_of_time
  AND (expiry_date IS NULL OR expiry_date > as_of_time)
LIMIT 1;
$$;-- ============================================================================
-- SCD Function
-- ============================================================================
CREATE OR REPLACE FUNCTION get_version_history_product(
natural_key_values jsonb
)
RETURNS SETOF catalog.tb_product
LANGUAGE plpgsql
AS $$
SELECT *
FROM catalog.tb_product
WHERE product_code = (natural_key_values->>'product_code')::TEXT
ORDER BY effective_date DESC;
$$;
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE catalog.tb_product IS
'Product entity.

@fraiseql:type
trinity: true
@fraiseql:pattern:temporal_scd_type2_helper
';

-- Trinity Pattern columns
COMMENT ON COLUMN catalog.tb_product.pk_product IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN catalog.tb_product.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN catalog.tb_product.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN catalog.tb_product.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN catalog.tb_product.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN catalog.tb_product.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN catalog.tb_product.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN catalog.tb_product.deleted_by IS 'User or system who deleted the record.';