-- ============================================================================
-- Table: crm.tb_task
-- ============================================================================
-- [Table: TAS | Task entity for CRM]
-- ============================================================================

CREATE TABLE crm.tb_task (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_task INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Multi-Tenancy: Denormalized from JWT (CRITICAL for security)
    -- ========================================================================
    tenant_id UUID NOT NULL,

    -- ========================================================================
    -- Multi-Tenancy: Optional business FK to organization
    -- ========================================================================
    -- Note: Only add fk_organization if entity belongs to specific org unit
    -- (not just tenant isolation). Comment out if not needed.
    -- fk_organization INTEGER,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    title TEXT,
    description TEXT,
    priority TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_task_id_key UNIQUE (id)
    ,CONSTRAINT chk_tb_task_priority_enum CHECK (priority IN ('low', 'medium', 'high')));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================-- ============================================================================
-- Multi-Tenancy Indexes (CRITICAL for performance & RLS)
-- ============================================================================
CREATE INDEX idx_tb_task_tenant ON crm.tb_task(tenant_id);
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE crm.tb_task IS
'Task entity for CRM.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN crm.tb_task.pk_task IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN crm.tb_task.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Multi-Tenancy columns
COMMENT ON COLUMN crm.tb_task.tenant_id IS 'Denormalized tenant identifier from JWT token (security context).';
-- COMMENT ON COLUMN crm.tb_task.fk_organization IS 'Optional business FK to organization unit (uncomment if needed).';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN crm.tb_task.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN crm.tb_task.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN crm.tb_task.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN crm.tb_task.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN crm.tb_task.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN crm.tb_task.deleted_by IS 'User or system who deleted the record.';