-- ============================================================================
-- Table: crm.tb_testcontact
-- ============================================================================
-- [Table: TES | TestContact entity]
-- ============================================================================

CREATE TABLE crm.tb_testcontact (
    -- ========================================================================
    -- Trinity Pattern: INTEGER primary key for performance
    -- ========================================================================
    pk_testcontact INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ========================================================================
    -- Trinity Pattern: UUID for stable public API
    -- ========================================================================
    id UUID DEFAULT gen_random_uuid() NOT NULL,
    -- ========================================================================
    -- Business Fields
    -- ========================================================================
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    -- ========================================================================
    -- Foreign Keys (Trinity Pattern: INTEGER references)
    -- ========================================================================

    -- ========================================================================
    -- Audit Fields (Trinity Pattern standard)
    -- ========================================================================
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,

    -- ========================================================================
    -- Constraints
    -- ========================================================================
    CONSTRAINT tb_testcontact_id_key UNIQUE (id));

-- ============================================================================
-- Foreign Key Constraints (defined after table creation)
-- ============================================================================
-- ============================================================================
-- Documentation
-- ============================================================================
COMMENT ON TABLE crm.tb_testcontact IS
'TestContact entity.

@fraiseql:type
trinity: true';

-- Trinity Pattern columns
COMMENT ON COLUMN crm.tb_testcontact.pk_testcontact IS 'Internal INTEGER primary key used in joins and foreign keys.';
COMMENT ON COLUMN crm.tb_testcontact.id IS
'Public UUID identifier for external APIs and GraphQL.

@fraiseql:field
name: id
type: UUID!
required: true';
-- Business field columns (comments handled by CommentGenerator)

-- Foreign key columns (comments handled by CommentGenerator)

-- Audit field columns
COMMENT ON COLUMN crm.tb_testcontact.created_at IS 'Timestamp when the record was created.';
COMMENT ON COLUMN crm.tb_testcontact.created_by IS 'User or system who created the record.';
COMMENT ON COLUMN crm.tb_testcontact.updated_at IS 'Timestamp when the record was last updated.';
COMMENT ON COLUMN crm.tb_testcontact.updated_by IS 'User or system who last updated the record.';
COMMENT ON COLUMN crm.tb_testcontact.deleted_at IS 'Timestamp of soft deletion.';
COMMENT ON COLUMN crm.tb_testcontact.deleted_by IS 'User or system who deleted the record.';