"""Tests for test_metadata schema creation"""

from pathlib import Path


def test_test_metadata_schema_sql_exists():
    """Test metadata schema SQL file should exist"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    assert schema_file.exists()


def test_test_metadata_schema_contains_create_schema():
    """Schema SQL should contain CREATE SCHEMA statement"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()
    assert "CREATE SCHEMA IF NOT EXISTS test_metadata;" in content


def test_entity_test_config_table_complete():
    """Entity test config table should have all required columns"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    # Basic structure
    assert "CREATE TABLE test_metadata.tb_entity_test_config" in content
    assert "pk_entity_test_config INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in content

    # Entity identification
    assert "entity_name TEXT NOT NULL UNIQUE" in content
    assert "schema_name TEXT NOT NULL" in content
    assert "table_name TEXT NOT NULL" in content

    # UUID encoding
    assert "table_code INTEGER NOT NULL" in content
    assert "entity_code TEXT NOT NULL" in content
    assert "base_uuid_prefix TEXT NOT NULL" in content

    # Multi-tenancy
    assert "is_tenant_scoped BOOLEAN DEFAULT TRUE" in content
    assert "default_tenant_id UUID DEFAULT '22222222-2222-2222-2222-222222222222'" in content
    assert "default_user_id UUID DEFAULT '01232022-0000-0000-0000-000000000001'" in content

    # Seed data defaults
    assert "default_seed_count INTEGER DEFAULT 10" in content
    assert "seed_strategy TEXT DEFAULT 'realistic'" in content

    # Test generation flags
    assert "enable_crud_tests BOOLEAN DEFAULT TRUE" in content
    assert "enable_action_tests BOOLEAN DEFAULT TRUE" in content
    assert "enable_constraint_tests BOOLEAN DEFAULT TRUE" in content
    assert "enable_dedup_tests BOOLEAN DEFAULT FALSE" in content
    assert "enable_fk_tests BOOLEAN DEFAULT TRUE" in content

    # Metadata
    assert "source_yaml_path TEXT" in content
    assert "created_at TIMESTAMPTZ DEFAULT NOW()" in content
    assert "updated_at TIMESTAMPTZ DEFAULT NOW()" in content

    # Constraints
    assert (
        "CONSTRAINT valid_seed_strategy CHECK (seed_strategy IN ('realistic', 'edge_cases', 'performance', 'minimal'))"
        in content
    )


def test_field_generator_mapping_table_complete():
    """Field generator mapping table should have all required columns"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    # Basic structure
    assert "CREATE TABLE test_metadata.tb_field_generator_mapping" in content
    assert "pk_field_gen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in content
    assert (
        "fk_entity_test_config INTEGER NOT NULL REFERENCES test_metadata.tb_entity_test_config"
        in content
    )

    # Field identification
    assert "field_name TEXT NOT NULL" in content
    assert "field_type TEXT NOT NULL" in content
    assert "postgres_type TEXT NOT NULL" in content

    # Generator strategy
    assert "generator_type TEXT NOT NULL" in content
    assert "generator_function TEXT" in content
    assert "generator_params JSONB" in content

    # FK resolution
    assert "fk_target_entity TEXT" in content
    assert "fk_target_schema TEXT" in content
    assert "fk_target_table TEXT" in content
    assert "fk_target_pk_field TEXT" in content
    assert "fk_resolution_query TEXT" in content
    assert "fk_filter_conditions TEXT" in content
    assert "fk_dependencies TEXT[]" in content

    # Group leader pattern
    assert "generator_group TEXT" in content
    assert "is_group_leader BOOLEAN DEFAULT FALSE" in content
    assert "group_leader_field TEXT" in content
    assert "group_dependency_fields TEXT[]" in content

    # Constraints & validation
    assert "nullable BOOLEAN DEFAULT TRUE" in content
    assert "unique_constraint BOOLEAN DEFAULT FALSE" in content
    assert "validation_pattern TEXT" in content
    assert "check_constraint TEXT" in content

    # Seed data hints
    assert "example_values TEXT[]" in content
    assert "seed_distribution JSONB" in content
    assert "enum_values TEXT[]" in content

    # Metadata
    assert "priority_order INTEGER DEFAULT 100" in content
    assert "created_at TIMESTAMPTZ DEFAULT NOW()" in content

    # Constraints
    assert "UNIQUE (fk_entity_test_config, field_name)" in content
    assert (
        "CONSTRAINT valid_generator_type CHECK (generator_type IN ('random', 'fk_resolve', 'group_leader', 'group_dependent', 'fixed', 'sequence'))"
        in content
    )


def test_test_scenarios_table_complete():
    """Test scenarios table should have all required columns"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    # Basic structure
    assert "CREATE TABLE test_metadata.tb_test_scenarios" in content
    assert "pk_scenario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in content
    assert (
        "fk_entity_test_config INTEGER NOT NULL REFERENCES test_metadata.tb_entity_test_config"
        in content
    )

    # Scenario identification
    assert "scenario_code INTEGER NOT NULL" in content
    assert "scenario_name TEXT NOT NULL" in content
    assert "scenario_type TEXT NOT NULL" in content

    # Test generation
    assert "test_function_name TEXT" in content
    assert "target_action TEXT" in content
    assert "input_overrides JSONB" in content
    assert "expected_result TEXT NOT NULL" in content
    assert "expected_error_code TEXT" in content
    assert "expected_status_pattern TEXT" in content

    # Seed data
    assert "seed_count INTEGER DEFAULT 1" in content
    assert "requires_dependencies BOOLEAN DEFAULT TRUE" in content
    assert "dependency_entities TEXT[]" in content

    # Test execution
    assert "setup_sql TEXT" in content
    assert "teardown_sql TEXT" in content

    # Metadata
    assert "description TEXT" in content
    assert "test_category TEXT" in content
    assert "enabled BOOLEAN DEFAULT TRUE" in content
    assert "created_at TIMESTAMPTZ DEFAULT NOW()" in content

    # Constraints
    assert "UNIQUE (fk_entity_test_config, scenario_code)" in content
    assert (
        "CONSTRAINT valid_scenario_type CHECK (scenario_type IN ('happy_path', 'constraint_violation', 'dedup', 'custom_action', 'fk_violation', 'performance'))"
        in content
    )
    assert (
        "CONSTRAINT valid_expected_result CHECK (expected_result IN ('success', 'error'))"
        in content
    )


def test_all_indexes_created():
    """Schema should contain all index definitions"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    # Entity config indexes
    assert (
        "CREATE INDEX idx_entity_test_config_entity_name ON test_metadata.tb_entity_test_config(entity_name)"
        in content
    )
    assert (
        "CREATE INDEX idx_entity_test_config_schema ON test_metadata.tb_entity_test_config(schema_name)"
        in content
    )

    # Field generator indexes
    assert (
        "CREATE INDEX idx_field_gen_entity ON test_metadata.tb_field_generator_mapping(fk_entity_test_config)"
        in content
    )
    assert (
        "CREATE INDEX idx_field_gen_type ON test_metadata.tb_field_generator_mapping(generator_type)"
        in content
    )
    assert (
        "CREATE INDEX idx_field_gen_group ON test_metadata.tb_field_generator_mapping(generator_group) WHERE generator_group IS NOT NULL"
        in content
    )

    # Scenario indexes
    assert (
        "CREATE INDEX idx_scenario_entity ON test_metadata.tb_test_scenarios(fk_entity_test_config)"
        in content
    )
    assert (
        "CREATE INDEX idx_scenario_type ON test_metadata.tb_test_scenarios(scenario_type)"
        in content
    )
    assert (
        "CREATE INDEX idx_scenario_enabled ON test_metadata.tb_test_scenarios(enabled) WHERE enabled = TRUE"
        in content
    )


def test_comments_added():
    """Schema should contain helpful comments"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    assert (
        "COMMENT ON SCHEMA test_metadata IS 'Test metadata for automated test and seed data generation'"
        in content
    )
    assert (
        "COMMENT ON TABLE test_metadata.tb_entity_test_config IS 'High-level configuration for each entity''s testing'"
        in content
    )
    assert (
        "COMMENT ON TABLE test_metadata.tb_field_generator_mapping IS 'Describes how to generate values for each field'"
        in content
    )
    assert (
        "COMMENT ON TABLE test_metadata.tb_test_scenarios IS 'Define test scenarios for each entity'"
        in content
    )


def test_sql_syntax_basic_validation():
    """Schema SQL should have basic valid SQL syntax"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    # Check for balanced parentheses
    open_parens = content.count("(")
    close_parens = content.count(")")
    assert open_parens == close_parens, (
        f"Unbalanced parentheses: {open_parens} open, {close_parens} close"
    )

    # Check for balanced quotes (basic check)
    single_quotes = content.count("'") - content.count("''")  # Account for escaped quotes
    assert single_quotes % 2 == 0, f"Odd number of single quotes: {single_quotes}"

    # Check for required SQL keywords
    assert "CREATE SCHEMA" in content
    assert "CREATE TABLE" in content
    assert "PRIMARY KEY" in content
    assert "REFERENCES" in content
    assert "CREATE INDEX" in content

    # Check that statements end with semicolons (basic check)
    lines = [
        line.strip()
        for line in content.split("\n")
        if line.strip() and not line.strip().startswith("--")
    ]
    sql_statements = " ".join(lines).split(";")
    # Should have multiple statements separated by semicolons
    assert len([s for s in sql_statements if s.strip()]) > 5, "Should have multiple SQL statements"


def test_schema_file_structure():
    """Schema file should have proper structure and organization"""
    schema_file = Path("migrations/test_metadata_schema.sql")
    content = schema_file.read_text()

    lines = content.split("\n")

    # Should start with header comment
    assert lines[0].startswith("-- Test Metadata Schema")

    # Should contain CREATE SCHEMA
    assert any("CREATE SCHEMA IF NOT EXISTS test_metadata" in line for line in lines)

    # Should have table definitions in order
    table_order = []
    for line in lines:
        if "CREATE TABLE test_metadata." in line:
            table_name = line.split("CREATE TABLE test_metadata.")[1].split(" ")[0]
            table_order.append(table_name)

    expected_order = ["tb_entity_test_config", "tb_field_generator_mapping", "tb_test_scenarios"]
    assert table_order == expected_order, (
        f"Tables not in expected order. Got: {table_order}, Expected: {expected_order}"
    )

    # Should end with comments
    assert any("COMMENT ON SCHEMA" in line for line in lines)
    assert any("COMMENT ON TABLE" in line for line in lines)
