"""
Tests for tv_ file splitting and content structuring

Tests splitting monolithic tv_ output into individual entity files.
"""


from src.generators.schema.table_view_file_generator import TableViewFileGenerator, TableViewFile
from src.core.ast_models import EntityDefinition, FieldDefinition, TableViewConfig, TableViewMode, FieldTier


class TestTableViewFileSplitting:
    """Test splitting tv_ generation into individual files"""

    def test_generate_individual_tv_files(self):
        """Should generate separate file per tv_ entity"""
        entities = [create_contact_entity(), create_company_entity()]

        generator = TableViewFileGenerator(entities)
        files = generator.generate_files()

        assert len(files) == 2
        # Note: Codes are now generated by registry, not hardcoded
        assert files[0].name == "tv_company"
        assert "CREATE TABLE" in files[0].content
        assert "tv_company" in files[0].content

        assert files[1].name == "tv_contact"
        assert "CREATE TABLE" in files[1].content
        assert "tv_contact" in files[1].content

    def test_tv_file_structure(self):
        """Should include all components in file"""
        entity = create_contact_entity()

        generator = TableViewFileGenerator([entity])
        files = generator.generate_files()

        assert len(files) == 1
        file = files[0]

        # Check all components present
        assert "CREATE TABLE" in file.content
        assert "CREATE INDEX" in file.content
        assert "CREATE OR REPLACE FUNCTION" in file.content  # refresh function
        assert "COMMENT ON TABLE" in file.content
        # Note: Triggers may not be implemented yet in this phase

    def test_dependency_order_preserved(self):
        """Should maintain topological order"""
        company = create_company_entity()
        contact = create_contact_entity()  # depends on company

        generator = TableViewFileGenerator([contact, company])
        files = generator.generate_files()

        # Company first, contact second (dependency order)
        assert files[0].name == "tv_company"
        assert files[1].name == "tv_contact"

    def test_file_content_is_complete_sql(self):
        """Should contain complete, valid SQL for each file"""
        entity = create_contact_entity()

        generator = TableViewFileGenerator([entity])
        files = generator.generate_files()

        assert len(files) == 1
        content = files[0].content

        # Should be valid SQL with proper structure
        assert content.strip().endswith(";")
        assert "-- Table View:" in content
        assert "crm.tv_contact" in content

    def test_fraiseql_annotations_included(self):
        """Should include FraiseQL annotations in file content"""
        entity = create_contact_entity()

        generator = TableViewFileGenerator([entity])
        files = generator.generate_files()

        assert len(files) == 1
        content = files[0].content

        # Should include FraiseQL annotations
        assert "-- FraiseQL Annotations:" in content
        assert "crm.tv_contact" in content

    def test_write_files_to_disk(self):
        """Should write files to disk with hierarchical structure"""
        import tempfile
        from pathlib import Path

        entity = create_contact_entity()
        generator = TableViewFileGenerator([entity])

        with tempfile.TemporaryDirectory() as temp_dir:
            output_dir = Path(temp_dir) / "output"
            written_paths = generator.write_files_to_disk(str(output_dir), dry_run=False)

            assert len(written_paths) == 1
            assert "tv_contact" in written_paths[0]
            assert "022" in written_paths[0]  # Should contain read-side code

            # Check file exists
            written_file = Path(written_paths[0])
            assert written_file.exists()
            assert written_file.is_file()

            # Check content
            with open(written_file) as f:
                content = f.read()
                assert "CREATE TABLE" in content
                assert "tv_contact" in content

    def test_write_files_to_disk_dry_run(self):
        """Should not write files in dry-run mode"""
        import tempfile
        from pathlib import Path

        entity = create_contact_entity()
        generator = TableViewFileGenerator([entity])

        with tempfile.TemporaryDirectory() as temp_dir:
            output_dir = Path(temp_dir) / "output"
            written_paths = generator.write_files_to_disk(str(output_dir), dry_run=True)

            assert len(written_paths) == 1
            assert "tv_contact" in written_paths[0]

            # File should not exist in dry-run
            written_file = Path(written_paths[0])
            assert not written_file.exists()

    def test_write_files_to_disk_no_entities(self):
        """Should handle case with no entities to write"""
        generator = TableViewFileGenerator([])

        written_paths = generator.write_files_to_disk(dry_run=True)
        assert written_paths == []


class TestTableViewFileDataclass:
    """Test TableViewFile dataclass"""

    def test_file_dataclass_creation(self):
        """Should create TableViewFile with correct attributes"""
        file = TableViewFile(
            code="0220110",
            name="tv_company",
            content="CREATE TABLE crm.tv_company (...);",
            dependencies=[]
        )

        assert file.code == "0220110"
        assert file.name == "tv_company"
        assert file.content == "CREATE TABLE crm.tv_company (...);"
        assert file.dependencies == []

    def test_file_with_dependencies(self):
        """Should handle files with dependencies"""
        file = TableViewFile(
            code="0220120",
            name="tv_contact",
            content="CREATE TABLE crm.tv_contact (...);",
            dependencies=["tv_company"]
        )

        assert file.dependencies == ["tv_company"]


# Helper functions for creating test entities

def create_contact_entity() -> EntityDefinition:
    """Create a test Contact entity"""
    return EntityDefinition(
        name="Contact",
        schema="crm",
        fields={
            "company": FieldDefinition(
                name="company",
                type_name="reference",
                tier=FieldTier.REFERENCE,
                reference_entity="Company"
            )
        },
        table_views=TableViewConfig(mode=TableViewMode.FORCE)
    )


def create_company_entity() -> EntityDefinition:
    """Create a test Company entity"""
    return EntityDefinition(
        name="Company",
        schema="crm",
        fields={},
        table_views=TableViewConfig(mode=TableViewMode.FORCE)
    )