from src.core.ast_models import EntityDefinition, FieldDefinition
from src.generators.schema.node_info_split import (
    generate_info_table_ddl,
    generate_node_info_split_ddl,
    generate_node_table_ddl,
    generate_unified_view_ddl,
    should_split_entity,
    split_entity_fields,
)


def test_should_split_entity_opt_in_false():
    """Test that should_split_entity returns False by default (opt-in only)"""
    entity = EntityDefinition(
        name="ComplexEntity",
        schema="test",
        fields={
            "field1": FieldDefinition(name="field1", type_name="text", nullable=False),
            "field2": FieldDefinition(name="field2", type_name="text", nullable=False),
            "field3": FieldDefinition(name="field3", type_name="text", nullable=False),
            "field4": FieldDefinition(name="field4", type_name="text", nullable=False),
            "field5": FieldDefinition(name="field5", type_name="text", nullable=False),
            "field6": FieldDefinition(name="field6", type_name="text", nullable=False),
            "field7": FieldDefinition(name="field7", type_name="text", nullable=False),
            "field8": FieldDefinition(name="field8", type_name="text", nullable=False),
            "field9": FieldDefinition(name="field9", type_name="text", nullable=False),
            "field10": FieldDefinition(name="field10", type_name="text", nullable=False),
            "field11": FieldDefinition(name="field11", type_name="text", nullable=False),
            "field12": FieldDefinition(name="field12", type_name="text", nullable=False),
            "field13": FieldDefinition(
                name="field13", type_name="text", nullable=False
            ),  # 13 fields
        },
    )

    # Should not auto-split even with >12 fields
    assert should_split_entity(entity) is False


def test_split_entity_fields():
    """Test splitting entity fields into node and info categories"""
    entity = EntityDefinition(
        name="TestEntity",
        schema="test",
        fields={
            "path": FieldDefinition(name="path", type_name="ltree", nullable=False),
            "fk_parent_testentity": FieldDefinition(
                name="fk_parent_testentity",
                type_name="ref",
                nullable=True,
                reference_entity="TestEntity",
            ),
            "business_field1": FieldDefinition(
                name="business_field1", type_name="text", nullable=False
            ),
            "business_field2": FieldDefinition(
                name="business_field2", type_name="text", nullable=False
            ),
        },
    )

    node_fields, info_fields = split_entity_fields(entity)

    # Node fields should contain hierarchy fields
    assert len(node_fields) == 2
    assert node_fields[0].name == "path"
    assert node_fields[1].name == "fk_parent_testentity"

    # Info fields should contain business fields
    assert len(info_fields) == 2
    assert info_fields[0].name == "business_field1"
    assert info_fields[1].name == "business_field2"


def test_generate_node_table_ddl():
    """Test generation of node table DDL"""
    entity = EntityDefinition(
        name="TestEntity",
        schema="test",
        fields={
            "path": FieldDefinition(name="path", type_name="ltree", nullable=False),
            "fk_parent_testentity": FieldDefinition(
                name="fk_parent_testentity",
                type_name="ref",
                nullable=True,
                reference_entity="TestEntity",
            ),
        },
    )

    ddl = generate_node_table_ddl(entity, "test")

    assert "CREATE TABLE test.tb_testentity_node" in ddl
    assert "pk_testentity INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE" in ddl
    assert "tenant_id UUID NOT NULL" in ddl
    assert "path ltree NOT NULL" in ddl
    assert "fk_parent_testentity INTEGER REFERENCES test.tb_testentity_node(pk_testentity)" in ddl
    assert "fk_testentity_info INTEGER NOT NULL" in ddl
    assert "created_at TIMESTAMPTZ NOT NULL DEFAULT now()" in ddl
    assert "UNIQUE (tenant_id, id)" in ddl
    assert "UNIQUE (tenant_id, path)" in ddl
    assert "CREATE INDEX idx_testentity_node_tenant" in ddl
    assert "CREATE INDEX idx_testentity_node_path" in ddl
    assert "CREATE INDEX idx_testentity_node_parent" in ddl
    assert "CREATE INDEX idx_testentity_node_info_fk" in ddl


def test_generate_info_table_ddl():
    """Test generation of info table DDL"""
    entity = EntityDefinition(
        name="TestEntity",
        schema="test",
        fields={
            "business_field1": FieldDefinition(
                name="business_field1", type_name="text", nullable=False
            ),
            "business_field2": FieldDefinition(
                name="business_field2", type_name="text", nullable=True
            ),
        },
    )

    ddl = generate_info_table_ddl(entity, "test")

    assert "CREATE TABLE test.tb_testentity_info" in ddl
    assert "pk_testentity_info INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE" in ddl
    assert "tenant_id UUID NOT NULL" in ddl
    assert "identifier TEXT NOT NULL" in ddl
    assert "sequence_number INTEGER NOT NULL DEFAULT 1" in ddl
    assert "display_identifier TEXT GENERATED ALWAYS AS" in ddl
    assert "business_field1 TEXT NOT NULL" in ddl
    assert "business_field2 TEXT" in ddl
    assert "created_at TIMESTAMPTZ NOT NULL DEFAULT now()" in ddl
    assert "updated_at TIMESTAMPTZ NOT NULL DEFAULT now()" in ddl
    assert "identifier_recalculated_at TIMESTAMPTZ" in ddl
    assert "UNIQUE (tenant_id, display_identifier)" in ddl
    assert "UNIQUE (identifier, sequence_number)" in ddl
    assert "CREATE INDEX idx_testentity_info_tenant" in ddl
    assert "CREATE INDEX idx_testentity_info_identifier" in ddl


def test_generate_unified_view_ddl():
    """Test generation of unified view DDL"""
    entity = EntityDefinition(
        name="TestEntity",
        schema="test",
        fields={
            "path": FieldDefinition(name="path", type_name="ltree", nullable=False),
            "fk_parent_testentity": FieldDefinition(
                name="fk_parent_testentity",
                type_name="ref",
                nullable=True,
                reference_entity="TestEntity",
            ),
            "business_field1": FieldDefinition(
                name="business_field1", type_name="text", nullable=False
            ),
            "business_field2": FieldDefinition(
                name="business_field2", type_name="text", nullable=True
            ),
        },
    )

    ddl = generate_unified_view_ddl(entity, "test")

    assert "CREATE VIEW test.v_testentity AS" in ddl
    assert "FROM test.tb_testentity_node n" in ddl
    assert "INNER JOIN test.tb_testentity_info i" in ddl
    assert "ON i.pk_testentity_info = n.fk_testentity_info" in ddl
    assert "n.pk_testentity," in ddl
    assert "n.id," in ddl
    assert "n.tenant_id," in ddl
    assert "n.path," in ddl
    assert "n.fk_parent_testentity," in ddl
    assert "i.identifier," in ddl
    assert "i.business_field1," in ddl
    assert "i.business_field2," in ddl
    assert "n.created_at," in ddl
    assert "i.updated_at," in ddl
    assert "n.deleted_at," in ddl
    assert "n.deleted_by," in ddl
    assert "i.identifier_recalculated_at," in ddl
    assert "n.path_updated_at," in ddl
    assert "n.path_updated_by" in ddl
    assert "WHERE n.deleted_at IS NULL;" in ddl
    assert "@fraiseql:type" in ddl
    assert "name: TestEntity" in ddl
    assert "schema: test" in ddl


def test_generate_node_info_split_ddl():
    """Test complete node+info split DDL generation"""
    entity = EntityDefinition(
        name="TestEntity",
        schema="test",
        fields={
            "path": FieldDefinition(name="path", type_name="ltree", nullable=False),
            "fk_parent_testentity": FieldDefinition(
                name="fk_parent_testentity",
                type_name="ref",
                nullable=True,
                reference_entity="TestEntity",
            ),
            "business_field1": FieldDefinition(
                name="business_field1", type_name="text", nullable=False
            ),
            "business_field2": FieldDefinition(
                name="business_field2", type_name="text", nullable=True
            ),
        },
    )

    ddl_statements = generate_node_info_split_ddl(entity, "test")

    assert len(ddl_statements) == 3
    assert "CREATE TABLE test.tb_testentity_node" in ddl_statements[0]
    assert "CREATE TABLE test.tb_testentity_info" in ddl_statements[1]
    assert "CREATE VIEW test.v_testentity AS" in ddl_statements[2]
