"""
Tests for Rust handler generation

Tests the generation of Actix Web HTTP handlers.
"""

import pytest
from src.generators.rust.handler_generator import RustHandlerGenerator
from src.core.ast_models import Entity, FieldDefinition


class TestBasicHandlers:
    """Test generation of basic CRUD handlers"""

    @pytest.fixture
    def generator(self):
        return RustHandlerGenerator()

    @pytest.fixture
    def simple_entity(self):
        return Entity(
            name="Contact",
            schema="crm",
            fields={
                "email": FieldDefinition(
                    name="email", type_name="text", nullable=False
                ),
                "phone": FieldDefinition(name="phone", type_name="text", nullable=True),
            },
        )

    def test_generate_get_handler(self, generator, simple_entity):
        """Test GET /:id handler generation"""
        result = generator.generate_get_handler(simple_entity)

        # Function signature
        assert "pub async fn get_contact(" in result
        assert "pool: web::Data<DbPool>" in result
        assert "contact_id: web::Path<Uuid>" in result
        assert ") -> Result<HttpResponse>" in result

        # Query call
        assert "ContactQueries::find_by_id(&mut conn, *contact_id)" in result
        assert "HttpResponse::Ok().json(contact)" in result
        assert "HttpResponse::NotFound().finish()" in result

    def test_generate_list_handler(self, generator, simple_entity):
        """Test GET / handler generation"""
        result = generator.generate_list_handler(simple_entity)

        # Function signature
        assert "pub async fn list_contacts(" in result
        assert "pool: web::Data<DbPool>" in result
        assert ") -> Result<HttpResponse>" in result

        # Query call
        assert "ContactQueries::list_active(&mut conn)" in result
        assert "HttpResponse::Ok().json(contacts)" in result

    def test_generate_create_handler(self, generator, simple_entity):
        """Test POST / handler generation"""
        result = generator.generate_create_handler(simple_entity)

        # Function signature
        assert "pub async fn create_contact(" in result
        assert "pool: web::Data<DbPool>" in result
        assert "new_contact: web::Json<NewContact>" in result
        assert ") -> Result<HttpResponse>" in result

        # Query call
        assert "ContactQueries::create(&mut conn, new_contact.into_inner())" in result
        assert "HttpResponse::Created().json(contact)" in result

    def test_generate_update_handler(self, generator, simple_entity):
        """Test PUT /:id handler generation"""
        result = generator.generate_update_handler(simple_entity)

        # Function signature
        assert "pub async fn update_contact(" in result
        assert "pool: web::Data<DbPool>" in result
        assert "contact_id: web::Path<Uuid>" in result
        assert "update_data: web::Json<UpdateContact>" in result
        assert ") -> Result<HttpResponse>" in result

        # Query call
        assert (
            "ContactQueries::update(&mut conn, *contact_id, update_data.into_inner())"
            in result
        )
        assert "HttpResponse::Ok().json(contact)" in result

    def test_generate_delete_handler(self, generator, simple_entity):
        """Test DELETE /:id handler generation"""
        result = generator.generate_delete_handler(simple_entity)

        # Function signature
        assert "pub async fn delete_contact(" in result
        assert "pool: web::Data<DbPool>" in result
        assert "contact_id: web::Path<Uuid>" in result
        assert ") -> Result<HttpResponse>" in result

        # Query call
        assert "ContactQueries::soft_delete(&mut conn, *contact_id)" in result
        assert "HttpResponse::NoContent().finish()" in result

    def test_generate_handler_imports(self, generator, simple_entity):
        """Test required imports are generated"""
        result = generator.generate_imports(simple_entity)

        assert "use actix_web::{web, HttpResponse, Result};" in result
        assert "use diesel::r2d2::{self, ConnectionManager};" in result
        assert "use diesel::PgConnection;" in result
        assert "use uuid::Uuid;" in result
        assert (
            "use super::super::models::{Contact, NewContact, UpdateContact};" in result
        )
        assert "use super::super::queries::ContactQueries;" in result

    def test_generate_handlers_file(self, generator, simple_entity):
        """Test complete handlers.rs file generation"""
        result = generator.generate_handlers_file(simple_entity)

        # File structure
        assert "// Generated by SpecQL" in result
        assert "pub type DbPool" in result
        assert "get_contact" in result
        assert "list_contacts" in result
        assert "create_contact" in result
        assert "update_contact" in result
        assert "delete_contact" in result


class TestRouteConfiguration:
    """Test generation of route configuration"""

    @pytest.fixture
    def generator(self):
        return RustHandlerGenerator()

    @pytest.fixture
    def simple_entity(self):
        return Entity(name="Contact", schema="crm", fields={})

    def test_generate_route_config(self, generator, simple_entity):
        """Test route configuration generation"""
        result = generator.generate_route_config(simple_entity)

        # Function signature
        assert "pub fn configure_contact_routes(cfg: &mut web::ServiceConfig)" in result

        # Route definitions
        assert 'web::scope("/contacts")' in result
        assert '.route("", web::get().to(list_contacts))' in result
        assert '.route("", web::post().to(create_contact))' in result
        assert '.route("/{contact_id}", web::get().to(get_contact))' in result
        assert '.route("/{contact_id}", web::put().to(update_contact))' in result
        assert '.route("/{contact_id}", web::delete().to(delete_contact))' in result

    def test_generate_route_imports(self, generator, simple_entity):
        """Test route configuration imports"""
        result = generator.generate_route_imports(simple_entity)

        assert "use actix_web::web;" in result
        assert (
            "use super::handlers::contact::{get_contact, list_contacts, create_contact, update_contact, delete_contact};"
            in result
        )
