-- Auto-generated tests for Contact entity
-- Generated by Team T-Test phase 1

-- Structure Tests for Contact
-- Auto-generated: 2025-11-09T20:06:24.571897
BEGIN;
SELECT plan(10);

-- Table exists
SELECT has_table(
    'crm'::name,
    'tb_contact'::name,
    'Contact table should exist'
);

-- Trinity pattern columns
SELECT has_column('crm', 'tb_contact', 'pk_contact', 'Has INTEGER PK');
SELECT has_column('crm', 'tb_contact', 'id', 'Has UUID id');
SELECT has_column('crm', 'tb_contact', 'identifier', 'Has TEXT identifier');

-- Audit columns
SELECT has_column('crm', 'tb_contact', 'created_at', 'Has created_at');
SELECT has_column('crm', 'tb_contact', 'updated_at', 'Has updated_at');
SELECT has_column('crm', 'tb_contact', 'deleted_at', 'Has deleted_at for soft delete');

-- Primary key constraint
SELECT col_is_pk('crm', 'tb_contact', 'pk_contact', 'pk_contact is primary key');

-- UUID unique constraint
SELECT col_is_unique('crm', 'tb_contact', 'id', 'id is unique');

SELECT * FROM finish();
ROLLBACK;


-- CRUD Tests for Contact
-- Auto-generated: 2025-11-09T20:06:24.571950
BEGIN;
SELECT plan(15);

-- Test: CREATE succeeds
PREPARE create_test AS
    SELECT app.create_contact(
        '01232122-0000-0000-2000-000000000001'::UUID,
        '01232122-0000-0000-2000-000000000002'::UUID,
        '{"email": "test@example.com", "status": "lead", "first_name": "test_first_name"}'::JSONB
    );

SELECT lives_ok(
    'create_test',
    'create_contact should execute without error'
);

-- Test: CREATE returns success
DO $$
DECLARE
    v_result app.mutation_result;
BEGIN
    v_result := app.create_contact(
        '01232122-0000-0000-2000-000000000001'::UUID,
        '01232122-0000-0000-2000-000000000002'::UUID,
        '{"email": "test@example.com", "status": "lead", "first_name": "test_first_name"}'::JSONB
    );

    PERFORM ok(
        v_result.status = 'success',
        'CREATE should return success status'
    );

    PERFORM ok(
        v_result.object_data IS NOT NULL,
        'CREATE should return object_data'
    );

    PERFORM ok(
        (v_result.object_data->>'id') IS NOT NULL,
        'object_data should contain id'
    );
END $$;

-- Test: Record exists in database
DO $$
DECLARE
    v_result app.mutation_result;
    v_id UUID;
    v_count INTEGER;
BEGIN
    v_result := app.create_contact(
        '01232122-0000-0000-2000-000000000001'::UUID,
        '01232122-0000-0000-2000-000000000002'::UUID,
        '{"email": "test@example.com", "status": "lead", "first_name": "test_first_name"}'::JSONB
    );
    v_id := (v_result.object_data->>'id')::UUID;

    SELECT COUNT(*) INTO v_count
    FROM crm.tb_contact
    WHERE id = v_id;

    PERFORM is(v_count, 1, 'Record should exist in table');
END $$;

SELECT * FROM finish();
ROLLBACK;
